package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

public final class C0899k implements C0446h {
    private static final Map f1027a = new HashMap();
    private static final Map f1028b = new HashMap();
    private static final Map f1029c = new HashMap();

    public C0899k() {
        f1027a.put(fw.AGREE_AND_PAY, "Zustimmen und zahlen");
        f1027a.put(fw.AND_OTHER_FUNDING_SOURCES, "und andere");
        f1027a.put(fw.AUTHENTICATING, "Authentifizierung");
        f1027a.put(fw.BACK_BUTTON, "Zurück");
        f1027a.put(fw.BACKUP_FUNDING_SOURCE, "Alternative");
        f1027a.put(fw.CANCEL, "Abbrechen");
        f1027a.put(fw.CARDTYPE_AMERICANEXPRESS, "American Express");
        f1027a.put(fw.CARDTYPE_CARTAAURA, "Carta Aura");
        f1027a.put(fw.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f1027a.put(fw.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f1027a.put(fw.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f1027a.put(fw.CARDTYPE_COFINOGA, "Cofinoga");
        f1027a.put(fw.CARDTYPE_DELTA, "Delta");
        f1027a.put(fw.CARDTYPE_DISCOVER, "Discover");
        f1027a.put(fw.CARDTYPE_ELECTRON, "Electron");
        f1027a.put(fw.CARDTYPE_JCB, "JCB");
        f1027a.put(fw.CARDTYPE_MAESTRO, "Maestro");
        f1027a.put(fw.CARDTYPE_MASTERCARD, "MasterCard");
        f1027a.put(fw.CARDTYPE_POSTEPAY, "Postepay");
        f1027a.put(fw.CARDTYPE_4ETOILES, "4 étoiles");
        f1027a.put(fw.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f1027a.put(fw.CARDTYPE_VISA, "Visa");
        f1027a.put(fw.CHANGE_PAYMENT_METHOD, "Zahlungsmethode ändern");
        f1027a.put(fw.CHECKING_ACCOUNT_FOR_INSTITUTION, "Girokonto");
        f1027a.put(fw.CHECKING_DEVICE, "Gerät wird überprüft…");
        f1027a.put(fw.CLEAR_CREDIT_CARD_INFO, "Kreditkartendaten löschen");
        f1027a.put(fw.CONFIRM, "Bestätigen");
        f1027a.put(fw.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Möchten Sie Ihre Kreditkartendaten wirklich löschen?");
        f1027a.put(fw.CONFIRM_CHARGE_CREDIT_CARD, "Kreditkarte belasten");
        f1027a.put(fw.CONFIRM_LOG_OUT, "Möchten Sie sich wirklich ausloggen?");
        f1027a.put(fw.CONFIRM_SEND_PAYMENT, "Zahlen");
        f1027a.put(fw.CONSENT_AGREEMENT_AGREE, "Zustimmen");
        f1027a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Konto eröffnet am");
        f1027a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Kontostatus");
        f1027a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Kontotyp");
        f1027a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Adresse");
        f1027a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Altersgruppe");
        f1027a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Geburtsdatum");
        f1027a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "E-Mail-Adresse");
        f1027a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Vollständiger Name");
        f1027a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Geschlecht");
        f1027a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Sprache");
        f1027a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Ländereinstellung");
        f1027a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefon");
        f1027a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Zeitzone");
        f1027a.put(fw.CONSENT_AGREEMENT_ATTRIBUTES, "Folgende Informationen weitergeben: %s.");
        f1027a.put(fw.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "PayPal Express verwenden.");
        f1027a.put(fw.CONSENT_AGREEMENT_INTRO, "%s bittet um folgende Zustimmung:");
        f1027a.put(fw.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Sie genehmigen die Weitergabe von Informationen über die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsmethoden</a>.");
        f1027a.put(fw.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Zahlungsquellen anzeigen, damit Sie bei der Zahlung wählen können.");
        f1027a.put(fw.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "Sie <a href='%1$s'>autorisieren Abbuchungen für zukünftige PayPal-Zahlungen</a> bei %2$s. Sie weisen PayPal an, die von %3$s geforderten Beträge zu zahlen.");
        f1027a.put(fw.CONSENT_AGREEMENT_LOYALTY_CARD, "Sie stimmen zu, dass der Händler seine Kundenkarte Ihrer E-Börse hinzufügt und sie dort verwaltet.");
        f1027a.put(fw.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Sie stimmen den <a href='%2$s'>Datenschutzgrundsätzen</a> und den <a href='%3$s'>Nutzungsbedingungen</a> von %1$s zu.");
        f1027a.put(fw.CONSENT_AGREEMENT_REQUEST_MONEY, "Sie gestatten dem Händler, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        f1027a.put(fw.CONSENT_AGREEMENT_SEND_MONEY, "Sie gestatten dem Händler, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        f1027a.put(fw.CONSENT_AGREEMENT_TITLE, "Zustimmen");
        f1027a.put(fw.EMAIL, "E-Mail-Adresse");
        f1027a.put(fw.ENVIRONMENT_MOCK_DATA, "Beispieldaten");
        f1027a.put(fw.ENVIRONMENT_SANDBOX, "Sandbox");
        f1027a.put(fw.EXPIRES_ON_DATE, "Gültig bis");
        f1027a.put(fw.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsmethoden verfügbar sind.</p>");
        f1027a.put(fw.FORGOT_PASSWORD, "Passwort vergessen?");
        f1027a.put(fw.FROM_ACCOUNT, "Von");
        f1027a.put(fw.FUTURE_PAYMENT_METHOD_QUESTION, "Wie möchten Sie Ihre weiteren Zahlungen an %1$s finanzieren?");
        f1027a.put(fw.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Für zukünftige PayPal-Zahlungen bei diesem Händler wird Ihre Standardzahlungsquelle verwendet. </p><p>Um diese Vereinbarung zu kündigen, loggen Sie sich in Ihr PayPal-Konto ein, rufen Sie <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> auf und entfernen diesen Händler von der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> für Zahlungen im Einzugsverfahren.</p><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p>");
        f1027a.put(fw.INTERNAL_ERROR, "Interner Fehler");
        f1027a.put(fw.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Durch Klicken auf den Button unten stimme ich den <a href='%1$s'>PayPal-Nutzungsbedingungen</a> zu und bestätige, dass ich bei dieser Transaktion die japanischen Gesetze und Vorschriften einhalte, einschließlich Sanktionen hinsichtlich Zahlungen nach Nordkorea oder in den Iran gemäß dem <a href='%2$s'>Gesetz über Devisen und internationalen Handel</a>.</p>");
        f1027a.put(fw.LOG_IN, "Einloggen");
        f1027a.put(fw.LOG_IN_TO_PAYPAL, "Login mit PayPal");
        f1027a.put(fw.LOG_OUT_BUTTON, "Ausloggen");
        f1027a.put(fw.LOG_OUT, "Ausloggen");
        f1027a.put(fw.OK, "OK");
        f1027a.put(fw.PASSWORD, "Passwort");
        f1027a.put(fw.PAY_AFTER_DELIVERY, "Bezahlung nach 14 Tagen");
        f1027a.put(fw.PAY_WITH, "Zahlen mit");
        f1027a.put(fw.PAY_WITH_CARD, "Mit Kreditkarte zahlen");
        f1027a.put(fw.PAYPAL_BALANCE, "PayPal-Guthaben");
        f1027a.put(fw.PAYPAL_CREDIT, "PayPal Credit");
        f1027a.put(fw.PHONE, "Handynr.");
        f1027a.put(fw.PIN, "PIN");
        f1027a.put(fw.PREFERRED_PAYMENT_METHOD, "Bevorzugte Zahlungsmethode");
        f1027a.put(fw.PRIVACY, "PayPal schützt Ihre <a href='%s'>Privatsphäre</a> und Ihre Finanzinformationen.");
        f1027a.put(fw.PROCESSING, "In Verarbeitung");
        f1027a.put(fw.REMEMBER_CARD, "Kreditkarte speichern");
        f1027a.put(fw.REQUEST_MONEY, "Geld anfordern");
        f1027a.put(fw.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf “Einstellungen”. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Partners.</p>");
        f1027a.put(fw.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Sparkonto");
        f1027a.put(fw.SEND_MONEY, "Geld senden");
        f1027a.put(fw.SERVER_PROBLEM, "Beim Datenaustausch mit den PayPal-Servern ist ein Problem aufgetreten. Bitte versuchen Sie es erneut.");
        f1027a.put(fw.SESSION_EXPIRED_MESSAGE, "Loggen Sie sich erneut bei PayPal ein.");
        f1027a.put(fw.SESSION_EXPIRED_TITLE, "Sitzung abgelaufen");
        f1027a.put(fw.SHIPPING_ADDRESS, "Lieferadresse");
        f1027a.put(fw.SIGN_UP, "Neu bei PayPal? Neu anmelden");
        f1027a.put(fw.STAY_LOGGED_IN, "Eingeloggt bleiben");
        f1027a.put(fw.SYSTEM_ERROR_WITH_CODE, "Systemfehler (%s). Bitte versuchen Sie es später noch einmal.");
        f1027a.put(fw.TRY_AGAIN, "Erneut versuchen");
        f1027a.put(fw.TWO_FA_REQUIRED_ERROR, "Einloggen nicht möglich, da in Ihrem Konto die Zwei-Faktor-Authentifizierung aktiviert ist.");
        f1027a.put(fw.TWO_FACTOR_AUTH_TITLE, "Sicherheitscode");
        f1027a.put(fw.TWO_FACTOR_AUTH_SUBTITLE, "Wir senden Ihnen eine SMS auf Ihr Handy. Diese enthält einen 6-stelligen Code, der fünf Minuten lang gültig ist.");
        f1027a.put(fw.TWO_FACTOR_AUTH_SENDING_DIALOG, "SMS senden");
        f1027a.put(fw.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "6-stelligen Sicherheitscode eingeben");
        f1027a.put(fw.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Ihre Handynummer");
        f1027a.put(fw.TWO_FACTOR_AUTH_SEND_SMS, "SMS senden");
        f1027a.put(fw.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "SMS erneut senden");
        f1027a.put(fw.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Einloggen nicht möglich, da in Ihrem Konto die Zwei-Faktor-Authentifizierung aktiviert ist. Aktivieren Sie über die PayPal-Website Ihren Sicherheitsschlüssel.");
        f1027a.put(fw.UNAUTHORIZED_DEVICE_MESSAGE, "Mit diesem Gerät sind keine Zahlungen möglich.");
        f1027a.put(fw.UNAUTHORIZED_DEVICE_TITLE, "Nicht autorisiertes Gerät");
        f1027a.put(fw.UNAUTHORIZED_MERCHANT_MESSAGE, "Zahlungen an diesen Händler sind nicht möglich (ungültige Client-ID).");
        f1027a.put(fw.UNAUTHORIZED_MERCHANT_TITLE, "Ungültiger Händler");
        f1027a.put(fw.UNEXPECTED_PAYMENT_FLOW, "Bei der Verarbeitung Ihrer Zahlung ist ein Problem aufgetreten. Bitte versuchen Sie es erneut.");
        f1027a.put(fw.UNKNOWN_FUNDING_SOURCE, "Nicht erkannte Zahlungsquelle");
        f1027a.put(fw.WE_ARE_SORRY, "Fehler");
        f1027a.put(fw.YOUR_ORDER, "Ihre Bestellung");
        f1027a.put(fw.ANDROID_OS_TOO_OLD, "Dieses Gerät kann nicht mit PayPal kommunizieren, weil seine Android-Version zu alt ist. Aktualisieren Sie Android oder versuchen Sie es mit einem neueren Gerät.");
        f1027a.put(fw.CLEAR_CC_ALERT_TITLE, "Kreditkarte löschen?");
        f1027a.put(fw.CONSENT_FAILED_ALERT_TITLE, "Zustimmung fehlgeschlagen");
        f1027a.put(fw.CONNECTION_FAILED_TITLE, "Keine Verbindung");
        f1027a.put(fw.LOGIN_FAILED_ALERT_TITLE, "Login nicht erfolgreich");
        f1027a.put(fw.LOGIN_WITH_EMAIL, "Mit Passwort einloggen");
        f1027a.put(fw.LOGIN_WITH_PHONE, "Mit PIN einloggen");
        f1027a.put(fw.ONE_MOMENT, "Einen Moment…");
        f1027a.put(fw.PAY_FAILED_ALERT_TITLE, "Zahlung fehlgeschlagen.");
        f1027a.put(fw.SCAN_CARD_ICON_DESCRIPTION, "Fotografieren");
        f1027a.put(fw.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Sicherheitscode falsch. Bitte versuchen Sie es erneut.");
        f1027a.put(fw.VIA_LABEL, "über");
        f1027a.put(fw.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "Systemfehler. Bitte versuchen Sie es später noch einmal.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Sie genehmigen die Weitergabe von Informationen über die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Sie genehmigen die Weitergabe von Informationen über die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Sie genehmigen die Weitergabe von Informationen über die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Sie genehmigen die Weitergabe von Informationen über die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Sie genehmigen die Weitergabe von Informationen über die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsmethoden</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Sie genehmigen die Weitergabe von Informationen über die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a> an den Händler.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Sie genehmigen die Weitergabe von Informationen über die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Sie genehmigen die Weitergabe von Informationen über die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Sie genehmigen die Weitergabe von Informationen über die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Sie genehmigen die Weitergabe von Informationen über die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsmethoden</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Sie genehmigen die Weitergabe von Informationen über die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Sie genehmigen die Weitergabe von Informationen über die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsmethoden</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        f1028b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p>Sie <a href='%1$s'>autorisieren Abbuchungen für zukünftige PayPal-Zahlungen</a> bei %2$s. Sie weisen PayPal an, die von %3$s geforderten Beträge zu zahlen.</p><p>Weitere Informationen finden Sie im <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPal-Vertrag über Abonnementzahlungen</a>.</p>");
        f1028b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p>Sie <a href='%1$s'>autorisieren Abbuchungen für zukünftige PayPal-Zahlungen</a> bei %2$s. Sie weisen PayPal an, die von %3$s geforderten Beträge zu zahlen.</p><p>Weitere Informationen finden Sie im <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPal-Vertrag über Abonnementzahlungen</a>.</p>");
        f1028b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "Sie <a href='%1$s'>autorisieren Abbuchungen</a> für zukünftige PayPal-Zahlungen. Sie stimmen zu und beauftragen PayPal, alle Beträge zu zahlen.");
        f1028b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "Sie <a href='%1$s'>autorisieren Abbuchungen</a> für zukünftige PayPal-Zahlungen. Sie stimmen zu und beauftragen PayPal, alle Beträge zu zahlen.");
        f1028b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "Sie <a href='%1$s'>autorisieren Abbuchungen</a> für zukünftige PayPal-Zahlungen. Sie stimmen zu und beauftragen PayPal, alle Beträge zu zahlen.");
        f1028b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Sie genehmigen Zahlungen aus Abbuchungsaufträgen, die auch dann gesendet werden, wenn Sie nicht bei PayPal eingeloggt sind. <a href='%1$s'>Weitere Bedingungen</a>, einschließlich Informationen zu Zahlungsmethoden und Hinweise zur Stornierung von Abbuchungsaufträgen.");
        f1028b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        f1028b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        f1028b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        f1028b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        f1028b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        f1028b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        f1028b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        f1028b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        f1028b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        f1028b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        f1028b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        f1028b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        f1028b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        f1028b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen in Ihrem PayPal-Konto verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen in Ihrem PayPal-Konto verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen in Ihrem PayPal-Konto verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>");
        f1028b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>Für Einkäufe mit PayPal verwenden wir Ihre Standardzahlungsquelle (PayPal-Guthaben, hinzugefügtes Bankkonto, Debit Card oder Kreditkarte, in dieser Reihenfolge). Wenn Ihre Standardzahlungsquelle nicht ausreichend gedeckt ist, kann Ihre Bank oder Ihr Kreditkartenanbieter eine Gebühr berechnen.</p><p>Wenn Sie diese Vereinbarung kündigen möchten, klicken Sie in Ihrem PayPal-Konto unter <strong>Mein Profil</strong> auf <strong>Einstellungen</strong> und anschließend neben “Login mit PayPal” auf <strong>Ändern</strong>.</p>");
        f1028b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>Für Einkäufe mit PayPal verwenden wir Ihr PayPal-Guthaben oder Ihre Standard-Kreditkarte oder -Debit Card.</p><p>Um diese Vereinbarung zu kündigen, loggen Sie sich in Ihr PayPal-Konto ein, rufen Sie <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> auf und entfernen diese Website oder App von der Liste.</p>");
        f1028b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>Für Einkäufe mit PayPal verwenden wir Ihre Standardzahlungsquelle.</p><p>Um diese Vereinbarung zu kündigen, loggen Sie sich in Ihr PayPal-Konto ein, rufen Sie <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> auf und entfernen diese Website oder App von der Liste.</p>");
        f1028b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Für zukünftige PayPal-Zahlungen bei diesem Händler wird Ihre Standardzahlungsquelle verwendet. </p><p>Um diese Vereinbarung zu kündigen, loggen Sie sich in Ihr PayPal-Konto ein, rufen Sie <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> auf und entfernen Sie diesen Händler von der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> für Zahlungen im Einzugsverfahren.</p><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p>");
        f1028b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>Für Einkäufe mit PayPal verwenden wir Ihre Standardzahlungsmethode.</p><p>Um diese Autorisierung zu stornieren, klicken Sie in Ihrem PayPal-Konto auf <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong>, und löschen Sie diesen Händler aus der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> für Zahlungen im Einzugsverfahren.</p>");
        f1028b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Autorisierung für zukünftige Zahlungen</strong></h1><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>Für Einkäufe mit PayPal verwenden wir Ihre Standardzahlungsquelle.</p><p>Um diese Autorisierung zu stornieren, klicken Sie in Ihrem PayPal-Konto auf <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong>, und löschen Sie diesen Händler aus der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> für Zahlungen im Einzugsverfahren.</p>");
        f1028b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>Für Einkäufe mit PayPal verwenden wir Ihr PayPal-Guthaben oder Ihre Standard-Kreditkarte oder -Debit Card.</p><p>Um diese Vereinbarung zu kündigen, loggen Sie sich in Ihr PayPal-Konto ein, rufen Sie <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> auf und entfernen diese Website oder App von der Liste.</p>");
        f1028b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>Für Einkäufe mit PayPal verwenden wir Ihre Standardzahlungsmethode.</p><p>Um diese Autorisierung zu stornieren, klicken Sie in Ihrem PayPal-Konto auf <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong>, und löschen Sie diesen Händler aus der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> für Zahlungen im Einzugsverfahren.</p>");
        f1028b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>Für Einkäufe mit PayPal verwenden wir Ihre Standardzahlungsmethode.</p><p>Um diese Autorisierung zu stornieren, klicken Sie in Ihrem PayPal-Konto auf <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong>, und löschen Sie diesen Händler aus der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> für Zahlungen im Einzugsverfahren.</p>");
        f1028b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>Für Einkäufe mit PayPal verwenden wir Ihre Standardzahlungsmethode.</p><p>Um diese Autorisierung zu stornieren, klicken Sie in Ihrem PayPal-Konto auf <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong>, und löschen Sie diesen Händler aus der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> für Zahlungen im Einzugsverfahren.</p>");
        f1028b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>PayPal verwendet zuerst Ihr PayPal-Guthaben, um Einkäufe zu bezahlen. Wenn Ihr Guthaben nicht für den gesamten Betrag ausreicht, werden die folgenden Zahlungsquellen in der angegebenen Reihenfolge verwendet: Bankkonto, PayPal Credit, Debit Card, Kreditkarte und/oder Lastschrift mit Sicherheitsprüfung.</p><p>Um diese Vereinbarung zu kündigen, klicken Sie in Ihrem PayPal-Konto auf <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> und löschen Sie diesen Händler aus der Liste.</p><p>Eventuell ist eine Zahlungsautorisierung erforderlich, damit Zahlungen künftig von Ihrem PayPal-Konto abgebucht werden können. Die Autorisierung wird storniert und es wird nichts abgebucht.</p>");
        f1028b.put("LOG_IN_TO_PAYPAL|AU", "Login mit PayPal");
        f1028b.put("LOG_IN_TO_PAYPAL|GB", "Login mit PayPal");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Partner weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie auf das Zahnrad. Klicken Sie dann unter <strong>Sicherheit</strong> auf <strong>Login mit PayPal</strong> und löschen Sie diesen Partner.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Partners.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf “Einstellungen”. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Partners.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie unter <strong>Mein Profil</strong> auf “Einstellungen”. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Partner weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie auf das Zahnrad. Klicken Sie dann unter <strong>Sicherheit</strong> auf <strong>Login mit PayPal</strong> und löschen Sie diesen Partner.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Partners.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Partner weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie auf das Zahnrad. Klicken Sie dann unter <strong>Sicherheit</strong> auf <strong>Login mit PayPal</strong> und löschen Sie diesen Partner.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Partners.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie unter <strong>Mein Profil</strong> auf “Einstellungen”. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich in Ihr PayPal-Konto ein, klicken Sie rechts oben auf das Zahnrad und danach auf <strong>Sicherheits-Center</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler. Im klassischen Design klicken Sie unter <strong>Mein Profil</strong> auf <strong>Kontoeinstellungen</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Partner weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie unter <strong>Mein Profil</strong> auf “Einstellungen”. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Partner.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Partners.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.it ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie unter <strong>Mein Profil</strong> auf “Einstellungen”. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie unter <strong>Mein Profil</strong> auf “Einstellungen”. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie unter <strong>Mein Profil</strong> auf “Einstellungen”. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Partner weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.ru ein, klicken Sie rechts oben auf das Zahnrad und danach auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Partner.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Partners.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie unter <strong>Mein Profil</strong> auf “Einstellungen”. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com.tr ein, klicken Sie rechts oben auf das Zahnrad und danach auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Partner.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf “Einstellungen”. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1028b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f1029c.put("AMOUNT_MISMATCH", "Warenkorbsumme stimmt nicht mit Gesamtbetrag überein.");
        f1029c.put("AUTHORIZATION_ALREADY_COMPLETED", "Diese Autorisierung ist bereits abgeschlossen.");
        f1029c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Autorisierung hat einen Status, der nicht storniert werden kann.");
        f1029c.put("AUTHORIZATION_EXPIRED", "Autorisierung ist abgelaufen.");
        f1029c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Der angeforderte Autorisierungscode existiert nicht.");
        f1029c.put("AUTHORIZATION_VOIDED", "Autorisierung wurde storniert.");
        f1029c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Nur die ursprüngliche Autorisierung kann erneut autorisiert werden. Bereits erneut autorisierte Zahlungen können nicht nochmals autorisiert werden.");
        f1029c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Erneute Autorisierungen während des Anerkennungszeitraums sind nicht möglich.");
        f1029c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Der Betrag übersteigt Ihr Limit.");
        f1029c.put("CARD_TOKEN_PAYER_MISMATCH", "Zugriff auf gespeicherte Kreditkartendaten nicht möglich.");
        f1029c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Die Kreditkartendaten sind ungültig. Bitte korrigieren Sie Ihre Eingabe und versuchen Sie es erneut.");
        f1029c.put("CREDIT_CARD_REFUSED", "Kreditkarte abgelehnt.");
        f1029c.put("CURRENCY_MISMATCH", "Die Währung beim Einzug muss mit der Währung der Autorisierung übereinstimmen.");
        f1029c.put("CURRENCY_NOT_ALLOWED", "Diese Währung wird von PayPal derzeit nicht unterstützt.");
        f1029c.put("DATA_RETRIEVAL", "Systemfehler. Bitte versuchen Sie es später noch einmal.");
        f1029c.put("DUPLICATE_REQUEST_ID", "Systemfehler. Versuchen Sie es später noch einmal.");
        f1029c.put("EXPIRED_CREDIT_CARD", "Kreditkarte abgelaufen");
        f1029c.put("EXPIRED_CREDIT_CARD_TOKEN", "Diese Kreditkarte ist nicht mehr gespeichert.\nBitte erneut senden.");
        f1029c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Funktion wird für diesen Anbieter nicht unterstützt.");
        f1029c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Für diese Transaktion wurde bereits eine Teilrückzahlung geleistet.");
        f1029c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Sofortzahlung wird für diesen Intent nicht unterstützt.");
        f1029c.put("INSTRUMENT_DECLINED", "Ihre ausgewählte Zahlungsquelle wurde nicht akzeptiert. Wählen Sie eine andere Zahlungsquelle.");
        f1029c.put("INSUFFICIENT_FUNDS", "Käufer kann nicht zahlen – Guthaben nicht ausreichend.");
        f1029c.put("INTERNAL_SERVICE_ERROR", "Systemfehler. Versuchen Sie es später noch einmal.");
        f1029c.put("INVALID_ACCOUNT_NUMBER", "Diese Kontonummer existiert nicht.");
        f1029c.put("INVALID_ARGUMENT", "Transaktion wegen eines ungültigen Arguments abgelehnt");
        f1029c.put("INVALID_CITY_STATE_ZIP", "Ungültige Kombination aus Ort/Bundesstaat/PLZ.");
        f1029c.put("INVALID_FACILITATOR_CONFIGURATION", "Diese Transaktion kann aufgrund einer ungültigen Facilitator-Konfiguration nicht verarbeitet werden.");
        f1029c.put("INVALID_PAYER_ID", "Systemfehler (ungültige Absender-ID). Bitte versuchen Sie es später noch einmal.");
        f1029c.put("INVALID_RESOURCE_ID", "Systemfehler. Versuchen Sie es später noch einmal.");
        f1029c.put("PAYEE_ACCOUNT_INVALID", "Die E-Mail-Adresse des Anbieters ist nicht bestätigt.");
        f1029c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Dieser Anbieter kann zurzeit keine Zahlungen empfangen.");
        f1029c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Die E-Mail-Adresse des Anbieters ist nicht bestätigt.");
        f1029c.put("PAYEE_ACCOUNT_RESTRICTED", "Dieser Anbieter kann zurzeit keine Zahlungen empfangen.");
        f1029c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Ihr Konto ist gesperrt oder geschlossen.");
        f1029c.put("PAYER_ACCOUNT_RESTRICTED", "Der Zugriff auf Ihr Konto ist eingeschränkt.");
        f1029c.put("PAYER_CANNOT_PAY", "Sie können diese Transaktion nicht mit PayPal bezahlen.");
        f1029c.put("PAYER_EMPTY_BILLING_ADDRESS", "Rechnungsadresse ist für Transaktionen mit Nicht-PayPal-Kreditkarten erforderlich.");
        f1029c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Zugriff auf gespeicherte Kreditkartendaten nicht möglich.");
        f1029c.put("PAYMENT_APPROVAL_EXPIRED", "Die Zahlungsgenehmigung ist abgelaufen.");
        f1029c.put("PAYMENT_EXPIRED", "Die Zahlung ist abgelaufen.");
        f1029c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Der Absender hat die Zahlung nicht genehmigt.");
        f1029c.put("PAYMENT_REQUEST_ID_INVALID", "PayPal-Anforderungs-ID ist ungültig. Versuchen Sie es später noch einmal.");
        f1029c.put("PAYMENT_STATE_INVALID", "Diese Anforderung ist aufgrund des aktuellen Zahlungsstatus ungültig.");
        f1029c.put("PERMISSION_DENIED", "Keine Genehmigung für die angeforderte Aktion.");
        f1029c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Die angeforderte Rückzahlung übersteigt den Betrag der ursprünglichen Transaktion.");
        f1029c.put("REFUND_TIME_LIMIT_EXCEEDED", "Diese Transaktion ist zu alt für eine Rückzahlung.");
        f1029c.put("REQUIRED_SCOPE_MISSING", "Systemfehler. Versuchen Sie es später noch einmal.");
        f1029c.put("TOO_MANY_REAUTHORIZATIONS", "Für diese Autorisierung sind keine weiteren Autorisierungen möglich.");
        f1029c.put("TRANSACTION_ALREADY_REFUNDED", "Für diese Transaktion wurde bereits eine Rückzahlung geleistet.");
        f1029c.put("TRANSACTION_LIMIT_EXCEEDED", "Der Betrag übersteigt Ihr Limit.");
        f1029c.put("TRANSACTION_REFUSED", "Die Transaktion wurde abgelehnt.");
        f1029c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Die Transaktion wurde abgelehnt.");
        f1029c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Einstellung im Händlerprofil: Bestimmte Transaktionen werden automatisch abgelehnt.");
        f1029c.put("UNKNOWN_ERROR", "Systemfehler. Versuchen Sie es später noch einmal.");
        f1029c.put("UNSUPPORTED_PAYEE_COUNTRY", "Ihr Land wird nicht unterstützt.");
        f1029c.put("VALIDATION_ERROR", "Die Zahlungsdaten sind ungültig. Bitte korrigieren und Eingabe wiederholen.");
        f1029c.put("ORDER_ALREADY_COMPLETED", "Bestellung ist bereits storniert, abgelaufen oder abgeschlossen.");
        f1029c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Die maximal zulässige Anzahl an Autorisierungen für die Bestellung wurde erreicht.");
        f1029c.put("ORDER_VOIDED", "Bestellung wurde storniert.");
        f1029c.put("ORDER_CANNOT_BE_VOIDED", "Bestellung kann in diesem Status nicht storniert werden.");
        f1029c.put("INVALID_EXPERIENCE_PROFILE_ID", "Systemfehler. Versuchen Sie es später noch einmal.");
        f1029c.put("UNAUTHORIZED_PAYMENT", "Der Händler akzeptiert diesen Zahlungstyp nicht.");
        f1029c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Währung wird bei Kartentyp nicht unterstützt.");
        f1029c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Kreditkartentyp wird nicht unterstützt.");
        f1029c.put("ADDRESS_ADDITION_ERROR", "Fehler beim Hinzufügen der Lieferadresse zum PayPal-Konto.");
        f1029c.put("DUPLICATE_TRANSACTION", "Doppelte Transaktion.");
        f1029c.put("INVALID_SHIPPING_ADDRESS", "Die angegebene Lieferadresse ist nicht gültig.");
        f1029c.put("PAYMENT_CREATION_ERROR", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten. Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto.");
        f1029c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten – Ihre Kreditkarte ist abgelaufen. Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto.");
        f1029c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten – Sofortzahlung erforderlich, z.B. mit Kreditkarte. Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto.");
        f1029c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten – bestätigte Kreditkarte erforderlich. Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto.");
        f1029c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten – für diese App muss in Ihrem Konto eine Telefonnummer hinterlegt sein. Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto.");
        f1029c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten – Sie brauchen ein Konto mit einer gültigen Zahlungsquelle (Bankkonto oder Zahlungskarte). Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto.");
        f1029c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten – Ihr Konto ist im Minus. Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto.");
        f1029c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten – Sie haben Ihr Sendelimit erreicht. Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto.");
        f1029c.put("AUTH_RC_RISK_FAILURE", "Aufgrund von Risikomodellen abgelehnt");
        f1029c.put("AUTH_RC_OFAC_BLOCKED_IP", "Nicht autorisierter Client");
        f1029c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Nicht autorisierter Client");
        f1029c.put("invalid_user", "Benutzername/Passwort nicht korrekt. Bitte versuchen Sie es erneut.");
        f1029c.put("locked_user", "Ihr PayPal-Konto wurde vorübergehend gesperrt. Versuchen Sie es später noch einmal oder entsperren Sie Ihr Konto über www.paypal.com.");
        f1029c.put("max_attempts_exceeded", "Zu viele fehlgeschlagene Logins. Versuchen Sie es später noch einmal.");
        f1029c.put("invalid_request", "Es ist ein Fehler aufgetreten.");
        f1029c.put("unauthorized_client", "Anforderung nicht autorisiert.");
        f1029c.put("access_denied", "Anforderung nicht autorisiert.");
        f1029c.put("unsupported_response_type", "Es ist ein Fehler aufgetreten.");
        f1029c.put("invalid_scope", "Anforderung nicht autorisiert.");
        f1029c.put("server_error", "Systemfehler. Bitte versuchen Sie es später noch einmal.");
        f1029c.put("temporarily_unavailable", "Systemfehler. Versuchen Sie es später noch einmal.");
        f1029c.put("stepup_required", "Wir können Sie zurzeit nicht einloggen. Versuchen Sie es später noch einmal, oder loggen Sie sich aus Sicherheitsgründen über die PayPal-Website ein.");
    }

    public final String mo2147a() {
        return "de";
    }

    public final /* synthetic */ String mo2148a(Enum enumR, String str) {
        fw fwVar = (fw) enumR;
        String str2 = fwVar.toString() + "|" + str;
        return f1028b.containsKey(str2) ? (String) f1028b.get(str2) : (String) f1027a.get(fwVar);
    }

    public final String mo2149a(String str) {
        return (String) f1029c.get(str);
    }
}
