package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

public final class C0898j implements C0446h {
    private static final Map f1024a = new HashMap();
    private static final Map f1025b = new HashMap();
    private static final Map f1026c = new HashMap();

    public C0898j() {
        f1024a.put(fw.AGREE_AND_PAY, "Accepter og betal");
        f1024a.put(fw.AND_OTHER_FUNDING_SOURCES, "og andre");
        f1024a.put(fw.AUTHENTICATING, "Godkender");
        f1024a.put(fw.BACK_BUTTON, "Tilbage");
        f1024a.put(fw.BACKUP_FUNDING_SOURCE, "Alternativ");
        f1024a.put(fw.CANCEL, "Annuller");
        f1024a.put(fw.CARDTYPE_AMERICANEXPRESS, "American Express");
        f1024a.put(fw.CARDTYPE_CARTAAURA, "Carta Aura");
        f1024a.put(fw.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f1024a.put(fw.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f1024a.put(fw.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f1024a.put(fw.CARDTYPE_COFINOGA, "Cofinoga");
        f1024a.put(fw.CARDTYPE_DELTA, "Delta");
        f1024a.put(fw.CARDTYPE_DISCOVER, "Discover");
        f1024a.put(fw.CARDTYPE_ELECTRON, "Electron");
        f1024a.put(fw.CARDTYPE_JCB, "JCB");
        f1024a.put(fw.CARDTYPE_MAESTRO, "Maestro");
        f1024a.put(fw.CARDTYPE_MASTERCARD, "MasterCard");
        f1024a.put(fw.CARDTYPE_POSTEPAY, "Postepay");
        f1024a.put(fw.CARDTYPE_4ETOILES, "4 étoiles");
        f1024a.put(fw.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f1024a.put(fw.CARDTYPE_VISA, "Visa");
        f1024a.put(fw.CHANGE_PAYMENT_METHOD, "Skift betalingsmetode");
        f1024a.put(fw.CHECKING_ACCOUNT_FOR_INSTITUTION, "Checkkonto");
        f1024a.put(fw.CHECKING_DEVICE, "Kontrollerer enheden …");
        f1024a.put(fw.CLEAR_CREDIT_CARD_INFO, "Slet kortoplysninger");
        f1024a.put(fw.CONFIRM, "Bekræft");
        f1024a.put(fw.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Er du sikker på, at du vil slette kortoplysningerne?");
        f1024a.put(fw.CONFIRM_CHARGE_CREDIT_CARD, "Træk på kort");
        f1024a.put(fw.CONFIRM_LOG_OUT, "Vil du logge af PayPal?");
        f1024a.put(fw.CONFIRM_SEND_PAYMENT, "Betal");
        f1024a.put(fw.CONSENT_AGREEMENT_AGREE, "Accepter");
        f1024a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Dato for oprettelse af konto");
        f1024a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Kontostatus");
        f1024a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Kontotype");
        f1024a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Adresse");
        f1024a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Aldersgruppe");
        f1024a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Fødselsdato");
        f1024a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "E-mailadresse");
        f1024a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Fulde navn");
        f1024a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Køn");
        f1024a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Sprog");
        f1024a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Landestandard");
        f1024a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefon");
        f1024a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Tidszone");
        f1024a.put(fw.CONSENT_AGREEMENT_ATTRIBUTES, "Del følgende: %s.");
        f1024a.put(fw.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Brug nem betaling.");
        f1024a.put(fw.CONSENT_AGREEMENT_INTRO, "%s beder dig om at:");
        f1024a.put(fw.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Del de <a href='%1$s'>betalingsmetoder</a>, der er tilknyttet din PayPal-konto.");
        f1024a.put(fw.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Aktiver visning af dine betalingsmåder, så du kan vælge.");
        f1024a.put(fw.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Godkende, at der trækkes penge</a> for fremtidige køb hos %2$s, der betales via PayPal. Du beder os om at betale alle de beløb, som %3$s anmoder om.");
        f1024a.put(fw.CONSENT_AGREEMENT_LOYALTY_CARD, "Give dem tilladelse til at tilføje og administrere deres loyalitetskort i din PayPal-pung.");
        f1024a.put(fw.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Acceptere <a href='%2$s'>politikken om beskyttelse af personlige oplysninger</a> og <a href='%3$s'>brugeraftalen</a> for %1$s.");
        f1024a.put(fw.CONSENT_AGREEMENT_REQUEST_MONEY, "Giv dem tilladelse til at <a href='%1$s'>anmode om penge</a> på dine vegne, indtil du trækker din tilladelse tilbage.");
        f1024a.put(fw.CONSENT_AGREEMENT_SEND_MONEY, "Giv dem tilladelse til at <a href='%1$s'>overføre penge</a> på dine vegne, indtil du trækker din tilladelse tilbage.");
        f1024a.put(fw.CONSENT_AGREEMENT_TITLE, "Samtykke");
        f1024a.put(fw.EMAIL, "E-mailadresse");
        f1024a.put(fw.ENVIRONMENT_MOCK_DATA, "Simulerede data");
        f1024a.put(fw.ENVIRONMENT_SANDBOX, "Sandbox");
        f1024a.put(fw.EXPIRES_ON_DATE, "Udløber");
        f1024a.put(fw.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Betalingsmåder</strong></h1><p>PayPal deler kun oplysninger om, hvilke af dine betalingsmetoder der kan bruges.</p>");
        f1024a.put(fw.FORGOT_PASSWORD, "Glemt adgangskoden?");
        f1024a.put(fw.FROM_ACCOUNT, "Fra");
        f1024a.put(fw.FUTURE_PAYMENT_METHOD_QUESTION, "Hvordan vil du gerne betale %1$s i fremtiden?");
        f1024a.put(fw.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Din foretrukne betalingsmåde bruges til at betale for fremtidige PayPal-betalinger til denne webbutik.</p><p>Hvis du vil annullere denne aftale, skal du logge på din PayPal-konto, gå til <strong>Min profil</strong> &gt; <strong>Mine indstillinger</strong> &gt; <strong>Log på med PayPal</strong> og fjerne webbutikken fra listen.</p><p>Afsnittet Fast betaling i <a href='%s'>PayPals brugeraftale</a> finder anvendelse.</p><p>Appen kan simulere en lille prøvetransaktion for at sikre, at du kan betale med din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p>");
        f1024a.put(fw.INTERNAL_ERROR, "Intern fejl");
        f1024a.put(fw.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Ved at klikke på knappen nedenfor accepterer jeg vilkårene i <a href='%1$s'>PayPals brugeraftale</a>, og jeg erklærer mig i overensstemmelse med japanske love og regler, herunder sanktioner mod betalinger til Nordkorea og Iran i henhold til <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a> for at gennemføre transaktionen.</p>");
        f1024a.put(fw.LOG_IN, "Log på");
        f1024a.put(fw.LOG_IN_TO_PAYPAL, "Log på med PayPal");
        f1024a.put(fw.LOG_OUT_BUTTON, "Log af");
        f1024a.put(fw.LOG_OUT, "Log af");
        f1024a.put(fw.OK, "OK");
        f1024a.put(fw.PASSWORD, "Adgangskode");
        f1024a.put(fw.PAY_AFTER_DELIVERY, "Betal efter levering");
        f1024a.put(fw.PAY_WITH, "Betal med");
        f1024a.put(fw.PAY_WITH_CARD, "Betal med kort");
        f1024a.put(fw.PAYPAL_BALANCE, "PayPal-saldo");
        f1024a.put(fw.PAYPAL_CREDIT, "PayPal Credit");
        f1024a.put(fw.PHONE, "Telefon");
        f1024a.put(fw.PIN, "Pinkode");
        f1024a.put(fw.PREFERRED_PAYMENT_METHOD, "Foretrukken betalingsmetode");
        f1024a.put(fw.PRIVACY, "Vi beskytter dine <a href='%s'>personlige oplysninger</a> og betalingsoplysninger.");
        f1024a.put(fw.PROCESSING, "Behandler");
        f1024a.put(fw.REMEMBER_CARD, "Husk kort");
        f1024a.put(fw.REQUEST_MONEY, "Anmod om penge");
        f1024a.put(fw.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække tilladelsen tilbage, skal du logge på paypal.com, gå til sektionen <strong>Log på med PayPal</strong> under <strong>Min profil</strong> og fjerne webbutikken.</p><p>Vi er ikke ansvarlig for nogen af partnerens handlinger eller fejl.</p>");
        f1024a.put(fw.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Opsparingskonto");
        f1024a.put(fw.SEND_MONEY, "Overfør penge");
        f1024a.put(fw.SERVER_PROBLEM, "Der kunne ikke oprettes forbindelse til vores servere. Prøv igen.");
        f1024a.put(fw.SESSION_EXPIRED_MESSAGE, "Log på PayPal igen.");
        f1024a.put(fw.SESSION_EXPIRED_TITLE, "Sessionen er udløbet");
        f1024a.put(fw.SHIPPING_ADDRESS, "Forsendelsesadresse");
        f1024a.put(fw.SIGN_UP, "Har du ikke en PayPal-konto? Opret konto");
        f1024a.put(fw.STAY_LOGGED_IN, "Forbliv logget på");
        f1024a.put(fw.SYSTEM_ERROR_WITH_CODE, "Systemfejl (%s). Prøv igen senere.");
        f1024a.put(fw.TRY_AGAIN, "Prøv igen");
        f1024a.put(fw.TWO_FA_REQUIRED_ERROR, "Der kunne ikke logges på, da to-faktor-godkendelse er aktiveret for din konto.");
        f1024a.put(fw.TWO_FACTOR_AUTH_TITLE, "Sikkerhedskode");
        f1024a.put(fw.TWO_FACTOR_AUTH_SUBTITLE, "Send en sms til din telefon. Den 6-cifrede kode, som du modtager, er gyldig i 5 minutter.");
        f1024a.put(fw.TWO_FACTOR_AUTH_SENDING_DIALOG, "Afsende sms");
        f1024a.put(fw.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Angiv den 6-cifrede sikkerhedskode");
        f1024a.put(fw.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Dit mobilnummer");
        f1024a.put(fw.TWO_FACTOR_AUTH_SEND_SMS, "Send sms");
        f1024a.put(fw.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Send sms igen");
        f1024a.put(fw.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Der kunne ikke logges på, da to-faktor-godkendelse er aktiveret for din konto. Gå til vores websted for at aktivere din sikkerhedsnøgle.");
        f1024a.put(fw.UNAUTHORIZED_DEVICE_MESSAGE, "Du kan ikke betale med denne enhed.");
        f1024a.put(fw.UNAUTHORIZED_DEVICE_TITLE, "Uautoriseret enhed");
        f1024a.put(fw.UNAUTHORIZED_MERCHANT_MESSAGE, "Du kan ikke betale denne webbutik (ugyldigt klient-id).");
        f1024a.put(fw.UNAUTHORIZED_MERCHANT_TITLE, "Ugyldig webbutik");
        f1024a.put(fw.UNEXPECTED_PAYMENT_FLOW, "Betalingen blev ikke behandlet. Prøv igen.");
        f1024a.put(fw.UNKNOWN_FUNDING_SOURCE, "Ukendt betalingsmetode");
        f1024a.put(fw.WE_ARE_SORRY, "Vi beklager");
        f1024a.put(fw.YOUR_ORDER, "Din bestilling");
        f1024a.put(fw.ANDROID_OS_TOO_OLD, "Enheden kan ikke kommunikere med PayPal, fordi Android-versionen er for gammel. Du skal opgradere Android eller prøve en nyere enhed.");
        f1024a.put(fw.CLEAR_CC_ALERT_TITLE, "Vil du slette kortet?");
        f1024a.put(fw.CONSENT_FAILED_ALERT_TITLE, "Samtykke mislykkedes");
        f1024a.put(fw.CONNECTION_FAILED_TITLE, "Der blev ikke oprettet forbindelse");
        f1024a.put(fw.LOGIN_FAILED_ALERT_TITLE, "Du blev ikke logget på");
        f1024a.put(fw.LOGIN_WITH_EMAIL, "Log på med adgangskode");
        f1024a.put(fw.LOGIN_WITH_PHONE, "Log på med pinkode");
        f1024a.put(fw.ONE_MOMENT, "Et øjeblik …");
        f1024a.put(fw.PAY_FAILED_ALERT_TITLE, "Betalingen gik ikke igennem.");
        f1024a.put(fw.SCAN_CARD_ICON_DESCRIPTION, "Scan");
        f1024a.put(fw.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Forkert sikkerhedskode. Prøv igen.");
        f1024a.put(fw.VIA_LABEL, "Via");
        f1024a.put(fw.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "Systemfejl. Prøv igen senere.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Del oplysninger om de <a href='%1$s'>betalingsmåder</a>, der er tilknyttet din PayPal-konto.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Del oplysningerne om de <a href='%1$s'>betalingsmåder</a>, der er tilknyttet din PayPal-konto.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Del oplysninger om de <a href='%1$s'>betalingsmåder</a>, der er tilknyttet din PayPal-konto.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Del oplysninger om de <a href='%1$s'>betalingsmåder</a>, der er tilknyttet din PayPal-konto.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Del oplysninger om de <a href='%1$s'>betalingsmetoder</a>, der er tilknyttet din PayPal-konto.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Del oplysninger med vedkommende om de <a href='%1$s'>betalingsmåder</a>, der er tilknyttet din PayPal-konto.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Del de <a href='%1$s'>betalingsmåder</a>, der er tilknyttet din PayPal-konto.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Del de <a href='%1$s'>betalingsmåder</a>, der er tilknyttet din PayPal-konto.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Del oplysningerne om de <a href='%1$s'>betalingsmåder</a>, der er tilknyttet din PayPal-konto.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Del oplysninger om de <a href='%1$s'>betalingsmetoder</a>, der er tilknyttet din PayPal-konto.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Del oplysningerne om de <a href='%1$s'>betalingsmåder</a>, der er tilknyttet din PayPal-konto.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Del oplysninger om de <a href='%1$s'>betalingsmetoder</a>, der er tilknyttet din PayPal-konto.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Del dine <a href='%1$s'>betalingsmåder</a> med andre, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Godkende, at der trækkes penge</a> for fremtidige køb hos %2$s, der betales via PayPal. Du beder os om at betale alle de beløb, som %3$s anmoder om.</p><p>Læs <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>vores aftale om faste betalinger og fakturering</a> for at få flere oplysninger.</p>");
        f1025b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Godkende, at der trækkes penge</a> for fremtidige køb hos %2$s, der betales via PayPal. Du beder os om at betale alle de beløb, som %3$s anmoder om.</p><p>Læs <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>vores aftale om faste betalinger og fakturering</a> for at få flere oplysninger.</p>");
        f1025b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>Godkend, at der trækkes penge</a> for fremtidige køb, der betales via PayPal. Du beder PayPal om at betale alle beløb og godkender dette.");
        f1025b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>Godkend, at der trækkes penge</a> for fremtidige køb, der betales via PayPal. Du beder PayPal om at betale alle beløb og godkender dette.");
        f1025b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>Godkend, at der trækkes penge</a> for fremtidige køb, der betales via PayPal. Du beder PayPal om at betale alle beløb og godkender dette.");
        f1025b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Godkend på forhånd fremtidige betalinger fra din PayPal-konto uden at logge på PayPal hver gang. <a href='%1$s'>Se flere vilkår</a>, blandt andet betalingsmetoder, og hvordan du annullerer fremtidige betalinger.");
        f1025b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Give %2$s tilladelse til at <a href='%1$s'>anmode om penge</a> på dine vegne, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Give %2$s tilladelse til at <a href='%1$s'>anmode om penge</a> på dine vegne, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Give %2$s tilladelse til at <a href='%1$s'>anmode om penge</a> på dine vegne, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Give %2$s tilladelse til at <a href='%1$s'>anmode om penge</a> på dine vegne, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Give %2$s tilladelse til at <a href='%1$s'>anmode om penge</a> på dine vegne, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Give %2$s tilladelse til at <a href='%1$s'>anmode om penge</a> på dine vegne, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Give %2$s tilladelse til at <a href='%1$s'>anmode om penge</a> på dine vegne, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Give %2$s tilladelse til at <a href='%1$s'>overføre penge</a> på dine vegne, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Give %2$s tilladelse til at <a href='%1$s'>overføre penge</a> på dine vegne, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Give %2$s tilladelse til at <a href='%1$s'>overføre penge</a> på dine vegne, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Give %2$s tilladelse til at <a href='%1$s'>overføre penge</a> på dine vegne, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Give %2$s tilladelse til at <a href='%1$s'>overføre penge</a> på dine vegne, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Give %2$s tilladelse til at <a href='%1$s'>overføre penge</a> på dine vegne, indtil du trækker din tilladelse tilbage.");
        f1025b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Give %2$s tilladelse til at <a href='%1$s'>overføre penge</a> på dine vegne, indtil du trækker din tilladelse tilbage.");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsmåder, der kan bruges.</p>");
        f1025b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Appen kan simulere en lille prøvetransaktion for at sikre, at der kan trækkes penge på din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode (din PayPal-saldo, din tilknyttede bankkonto eller dit betalingskort i denne rækkefølge) vil blive brugt, når du betaler med PayPal. Bemærk, at din bank eller kortudsteder muligvis opkræver et gebyr, hvis der ikke er nok penge til at dække købet med din foretrukne betalingsmetode.</p><p>Hvis du vil annullere denne aftale, skal du logge på din PayPal-konto og gå til <strong>Min profil</strong>. Klik derefter på <strong>Mine indstillinger</strong> og <strong>Skift</strong> ud for “Log på med PayPal”.</p>");
        f1025b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Appen kan simulere en lille prøvetransaktion for at kontrollere, at der kan trækkes penge på din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din PayPal-saldo eller det primære betalingskort vil blive brugt, når du betaler med PayPal.</p><p>Hvis du vil annullere denne aftale, skal du logge på din PayPal-konto, gå til <strong>Min profil</strong> &gt; <strong>Mine indstillinger</strong> &gt; <strong>Log på med PayPal</strong> og fjerne denne webbutik fra listen.</p>");
        f1025b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Appen kan simulere en lille prøvetransaktion for at sikre, at der kan trækkes penge på din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode vil blive brugt, når du betaler med PayPal.</p><p>Hvis du vil annullere denne aftale, skal du logge på din PayPal-konto og gå til <strong>Min profil</strong> &gt; <strong>Indstillinger</strong> &gt; <strong>Log på med PayPal</strong> og fjerne denne webbutik fra listen.</p>");
        f1025b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Din foretrukne betalingsmåde vil blive brugt, når du betaler med PayPal igen i denne webbutik.</p><p>Hvis du vil annullere aftalen, skal du logge på din PayPal-konto, gå til <strong>Min profil</strong> &gt; <strong>Mine indstillinger</strong> &gt; <strong>Log på med PayPal</strong> og fjerne webbutikken fra listen.</p><p>Afsnittet Faste betalinger i <a href='%s'>PayPals brugeraftale</a> gælder.</p><p>Appen kan simulere en lille prøvebetaling for at kontrollere, at du kan betale med din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p>");
        f1025b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Godkendelse af fremtidig betaling</strong></h1><p>Appen kan simulere en lille prøvebetaling for at kontrollere, at der kan trækkes penge på din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode vil blive brugt, når du betaler med PayPal.</p><p>Hvis du vil annullere autorisationen, skal du logge på din PayPal-konto, gå til <strong>Min profil</strong> &gt; <strong>Mine kontoindstillinger</strong> &gt; <strong>Log på med PayPal</strong> og fjerne webbutikken fra listen.</p><p>Du kan finde flere oplysninger i afsnittet “Forhåndsgodkendte betalinger” i vores <a href='%s'>brugeraftale</a>.</p>");
        f1025b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Godkendelse af fremtidig betaling</strong></h1><p>Appen kan simulere en lille prøvetransaktion for at sikre, at der kan trækkes penge på din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode vil blive brugt, når du betaler med PayPal.</p><p>Hvis du vil annullere autorisationen, skal du logge på din PayPal-konto, gå til <strong>Min profil</strong> &gt; <strong>Mine kontoindstillinger</strong> &gt; <strong>Log på med PayPal</strong> og fjerne webbutikken fra listen.</p><p>Du kan finde flere oplysninger i afsnittet “Forhåndsgodkendte betalinger” i <a href='%s'>vores brugeraftale</a>.</p>");
        f1025b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Appen kan simulere en lille prøvetransaktion for at kontrollere, at der kan trækkes penge på din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din PayPal-saldo eller det primære betalingskort vil blive brugt, når du betaler med PayPal.</p><p>Hvis du vil annullere denne aftale, skal du logge på din PayPal-konto, gå til <strong>Min profil</strong> &gt; <strong>Mine indstillinger</strong> &gt; <strong>Log på med PayPal</strong> og fjerne denne webbutik fra listen.</p>");
        f1025b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Godkendelse af fremtidig betaling</strong></h1><p>Appen kan simulere en lille prøvebetaling for at kontrollere, at der kan trækkes penge på din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode vil blive brugt, når du betaler med PayPal.</p><p>Hvis du vil annullere autorisationen, skal du logge på din PayPal-konto, gå til <strong>Min profil</strong> &gt; <strong>Mine kontoindstillinger</strong> &gt; <strong>Log på med PayPal</strong> og fjerne webbutikken fra listen.</p><p>Du kan finde flere oplysninger i afsnittet “Forhåndsgodkendte betalinger” i vores <a href='%s'>brugeraftale</a>.</p>");
        f1025b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Godkendelse af fremtidig betaling</strong></h1><p>Appen kan simulere en lille prøvebetaling for at kontrollere, at der kan trækkes penge på din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode vil blive brugt, når du betaler med PayPal.</p><p>Hvis du vil annullere autorisationen, skal du logge på din PayPal-konto, gå til <strong>Min profil</strong> &gt; <strong>Mine kontoindstillinger</strong> &gt; <strong>Log på med PayPal</strong> og fjerne webbutikken fra listen.</p><p>Du kan finde flere oplysninger i afsnittet “Forhåndsgodkendte betalinger” i vores <a href='%s'>brugeraftale</a>.</p>");
        f1025b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Godkendelse af fremtidig betaling</strong></h1><p>Appen kan simulere en lille prøvebetaling for at kontrollere, at der kan trækkes penge på din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode vil blive brugt, når du betaler med PayPal.</p><p>Hvis du vil annullere autorisationen, skal du logge på din PayPal-konto, gå til <strong>Min profil</strong> &gt; <strong>Mine kontoindstillinger</strong> &gt; <strong>Log på med PayPal</strong> og fjerne webbutikken fra listen.</p><p>Du kan finde flere oplysninger i afsnittet “Forhåndsgodkendte betalinger” i vores <a href='%s'>brugeraftale</a>.</p>");
        f1025b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Vi trækker først penge på din PayPal-saldo for at betale for dit køb. Hvis der ikke er penge nok på saldoen, trækker vi pengene via din bankkonto, PayPal Credit, dit betalingskort og/eller eCheck i denne rækkefølge.</p><p>Hvis du vil annullere denne aftale, skal du gå til www.paypal.com, vælge <strong>Min profil</strong> &gt; <strong>Mine indstillinger</strong> &gt; <strong>Log på med PayPal</strong> og fjerne denne webbutik fra listen.</p><p>Det kan være nødvendigt, at du autoriserer en lille betaling for at kontrollere, at der kan trækkes penge på din PayPal-konto i fremtiden. Betalingen vil blive annulleret, og der vil ikke blive trukket nogen penge.</p>");
        f1025b.put("LOG_IN_TO_PAYPAL|AU", "Log på med PayPal");
        f1025b.put("LOG_IN_TO_PAYPAL|GB", "Log på med PayPal");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med partneren.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på din PayPal-konto og klikke på tandhjulsikonet. Gå til <strong>Sikkerhed</strong>, vælg <strong>Log på med PayPal</strong>, og fjern partneren.</p><p>PayPal er ikke ansvarlig for nogen af partnerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække tilladelsen tilbage, skal du logge på paypal.com, gå til sektionen <strong>Log på med PayPal</strong> under <strong>Min profil</strong> og fjerne forhandleren.</p><p>Vi er ikke ansvarlig for nogen af partnerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på din PayPal-konto, gå til <strong>Log på med PayPal</strong> under <strong>Min profil</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med partneren.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på din PayPal-konto og klikke på tandhjulsikonet. Gå til <strong>Sikkerhed</strong>, vælg <strong>Log på med PayPal</strong>, og fjern partneren.</p><p>PayPal er ikke ansvarlig for nogen af partnerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med partneren.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på din PayPal-konto og klikke på tandhjulsikonet. Gå til <strong>Sikkerhed</strong>, vælg <strong>Log på med PayPal</strong>, og fjern partneren.</p><p>PayPal er ikke ansvarlig for nogen af partnerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på din PayPal-konto, gå til <strong>Log på med PayPal</strong> under <strong>Min profil</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal på logge på din PayPal-konto, klikke på tandhjulsikonet øverst til højre, vælge <strong>Sikkerhedscentret</strong>, vælge <strong>Log på med PayPal</strong> og fjerne webbutikken. Hvis du stadig bruger det tidligere kontolayout, skal du gå til <strong>Min profil</strong>, vælge <strong>Mine kontoindstillinger</strong>, vælge <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>Vi er ikke ansvarlig for nogen af webbutikkens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med partneren.</p><p>Hvis du vil trække din tilladelse tilbage, skal på logge på din PayPal-konto, gå til <strong>Log på med PayPal</strong> under <strong>Min profil</strong> og fjerne partneren.</p><p>PayPal er ikke ansvarlig for nogen af partnerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.it, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, finde sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på din PayPal-konto, gå til <strong>Log på med PayPal</strong> under <strong>Min profil</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på din PayPal-konto, gå til <strong>Log på med PayPal</strong> under <strong>Min profil</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på din PayPal-konto, gå til <strong>Log på med PayPal</strong> under <strong>Min profil</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med partneren.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.ru, klikke på tandhjulsikonet øverst til højre, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong>og fjerne partneren.</p><p>PayPal er ikke ansvarlig for nogen af partnerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på din PayPal-konto, gå til <strong>Log på med PayPal</strong> under <strong>Min profil</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.tr, klikke på tandhjulsikonet øverst til højre, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong>og fjerne partneren.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække tilladelsen tilbage, skal du logge på paypal.com, gå til sektionen <strong>Log på med PayPal</strong> under <strong>Min profil</strong> og fjerne webbutikken.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1025b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil trække din tilladelse tilbage, skal du logge på paypal.com, gå til <strong>Min profil</strong>, vælge fanen <strong>Sikkerhed</strong>, gå til sektionen <strong>Log på med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        f1026c.put("AMOUNT_MISMATCH", "Beløbet i indkøbskurven stemmer ikke overens med salgsbeløb.");
        f1026c.put("AUTHORIZATION_ALREADY_COMPLETED", "Autorisationen er allerede gået igennem.");
        f1026c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Autorisationen kan ikke annulleres.");
        f1026c.put("AUTHORIZATION_EXPIRED", "Autorisationen er udløbet.");
        f1026c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Det anmodede autorisationsnr. findes ikke.");
        f1026c.put("AUTHORIZATION_VOIDED", "Din autorisation er blevet annullleret.");
        f1026c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Du kan kun gentage den oprindelige autorisation og ikke en allerede gentaget autorisation.");
        f1026c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Du må ikke gentage en autorisation inden for garantiperioden.");
        f1026c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Beløbet overstiger den tilladte grænse.");
        f1026c.put("CARD_TOKEN_PAYER_MISMATCH", "De gemte kortoplysninger kan ikke åbnes.");
        f1026c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Kortoplysningerne er ugyldige. Ret oplysningerne, og send dem igen.");
        f1026c.put("CREDIT_CARD_REFUSED", "Kortet blev afvist.");
        f1026c.put("CURRENCY_MISMATCH", "Valuta for hentning skal være den samme som valutaen for autorisationen.");
        f1026c.put("CURRENCY_NOT_ALLOWED", "Valutaen understøttes ikke af PayPal.");
        f1026c.put("DATA_RETRIEVAL", "Systemfejl. Prøv igen senere.");
        f1026c.put("DUPLICATE_REQUEST_ID", "Systemfejl. Prøv igen senere.");
        f1026c.put("EXPIRED_CREDIT_CARD", "Kortet er udløbet");
        f1026c.put("EXPIRED_CREDIT_CARD_TOKEN", "Oplysningerne for dette kort er ikke længere gemt.\nSend igen.");
        f1026c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Sælgeren understøtter ikke denne funktion.");
        f1026c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Denne betaling er allerede blevet delvist tilbagebetalt.");
        f1026c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Den overførte hensigt understøtter ikke øjeblikkelig betaling.");
        f1026c.put("INSTRUMENT_DECLINED", "Den valgte betalingsmetode blev ikke godkendt. Vælg en anden betalingsmetode.");
        f1026c.put("INSUFFICIENT_FUNDS", "Kunden kan ikke betale – der er ikke penge nok.");
        f1026c.put("INTERNAL_SERVICE_ERROR", "Systemfejl. Prøv igen senere.");
        f1026c.put("INVALID_ACCOUNT_NUMBER", "Kontonummeret findes ikke.");
        f1026c.put("INVALID_ARGUMENT", "Betalingen blev afvist på grund af et ugyldigt argument");
        f1026c.put("INVALID_CITY_STATE_ZIP", "Ugyldig kombination af by, område og/eller postnummer.");
        f1026c.put("INVALID_FACILITATOR_CONFIGURATION", "Denne betaling kan ikke behandles på grund af en ugyldig formidlerkonfiguration.");
        f1026c.put("INVALID_PAYER_ID", "Systemfejl (ugyldigt betaler-id). Prøv igen senere.");
        f1026c.put("INVALID_RESOURCE_ID", "Systemfejl. Prøv igen senere.");
        f1026c.put("PAYEE_ACCOUNT_INVALID", "Sælgerkontoen har ikke en en bekræftet e-mailadresse.");
        f1026c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Denne sælger kan ikke tage imod betalinger i øjeblikket.");
        f1026c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Sælgerkontoen har ikke en en bekræftet e-mailadresse.");
        f1026c.put("PAYEE_ACCOUNT_RESTRICTED", "Denne sælger kan ikke tage imod betalinger i øjeblikket.");
        f1026c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Din konto er låst eller lukket.");
        f1026c.put("PAYER_ACCOUNT_RESTRICTED", "Din konto er begrænset.");
        f1026c.put("PAYER_CANNOT_PAY", "Du kan ikke bruge PayPal til denne betaling.");
        f1026c.put("PAYER_EMPTY_BILLING_ADDRESS", "Der skal angives en faktureringsadresse ved de kortbetalinger, der ikke foretages via PayPal.");
        f1026c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Kan ikke få adgang til gemte kortoplysninger.");
        f1026c.put("PAYMENT_APPROVAL_EXPIRED", "Godkendelsen af betalingen er udløbet.");
        f1026c.put("PAYMENT_EXPIRED", "Betalingen er udløbet.");
        f1026c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Betaleren har ikke godkendt betalingen.");
        f1026c.put("PAYMENT_REQUEST_ID_INVALID", "Id’et for PayPal-anmodningen er ugyldigt. Prøv igen senere.");
        f1026c.put("PAYMENT_STATE_INVALID", "Denne anmodning er ugyldig på grund af den aktuelle tilstand for betaling.");
        f1026c.put("PERMISSION_DENIED", "Du har ikke tilladelse til at udføre handlingen.");
        f1026c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Den anmodede tilbagebetaling overstiger det oprindelige beløb.");
        f1026c.put("REFUND_TIME_LIMIT_EXCEEDED", "Du kan ikke længere få tilbagebetalt denne betaling.");
        f1026c.put("REQUIRED_SCOPE_MISSING", "Systemfejl. Prøv igen senere.");
        f1026c.put("TOO_MANY_REAUTHORIZATIONS", "Du må ikke gentage denne autorisation flere gange.");
        f1026c.put("TRANSACTION_ALREADY_REFUNDED", "Betalingen er allerede blevet tilbagebetalt.");
        f1026c.put("TRANSACTION_LIMIT_EXCEEDED", "Beløbet overstiger den tilladte grænse.");
        f1026c.put("TRANSACTION_REFUSED", "Betalingen blev afvist.");
        f1026c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Betalingen blev afvist.");
        f1026c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Indstillingen for webbutikken er angivet til automatisk at afvise bestemte betalinger.");
        f1026c.put("UNKNOWN_ERROR", "Systemfejl. Prøv igen senere.");
        f1026c.put("UNSUPPORTED_PAYEE_COUNTRY", "Dit land understøttes ikke.");
        f1026c.put("VALIDATION_ERROR", "Betalingsoplysningerne er ugyldige. Ret oplysningerne, og send dem igen.");
        f1026c.put("ORDER_ALREADY_COMPLETED", "Bestillingen er allerede blevet annulleret, er udløbet eller er blevet sendt.");
        f1026c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Det maksimale antal autorisationer for bestillingen er nået.");
        f1026c.put("ORDER_VOIDED", "Bestillingen er blevet annulleret.");
        f1026c.put("ORDER_CANNOT_BE_VOIDED", "Bestillingen kan ikke annulleres.");
        f1026c.put("INVALID_EXPERIENCE_PROFILE_ID", "Systemfejl. Prøv igen senere.");
        f1026c.put("UNAUTHORIZED_PAYMENT", "Du kan ikke bruge denne betalingsmetode i denne webbutik.");
        f1026c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Du kan ikke betale med kortet i denne valuta.");
        f1026c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Korttypen understøttes ikke.");
        f1026c.put("ADDRESS_ADDITION_ERROR", "Der opstod fejl, da leveringsadressen blev føjet til din PayPal-konto.");
        f1026c.put("DUPLICATE_TRANSACTION", "Duplikeret betaling.");
        f1026c.put("INVALID_SHIPPING_ADDRESS", "Det angivne leveringsadresse er ugyldig.");
        f1026c.put("PAYMENT_CREATION_ERROR", "Betalingen blev ikke oprettet. Gå til vores websted for at kontrollere din konto.");
        f1026c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Betalingen blev ikke oprettet. Dit kort er udløbet. Gå til vores websted for at kontrollere din konto.");
        f1026c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Betalingen blev ikke oprettet. Du skal betale med det samme, f.eks. med et betalingskort. Gå til vores websted for at kontrollere din konto.");
        f1026c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Betalingen blev ikke oprettet. Du skal bekræfte dit kort. Gå til vores websted for at kontrollere din konto.");
        f1026c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Betalingen blev ikke oprettet. Du skal tilknytte et telefonnummer for at bruge denne app. Gå til vores websted for at kontrollere din konto.");
        f1026c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Betalingen blev ikke oprettet. Du skal knytte en gyldig betalingsmåde til kontoen, f.eks. et betalingskort. Gå til vores websted for at kontrollere din konto.");
        f1026c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Betalingen blev ikke oprettet. Der er et underskud på din konto. Gå til vores websted for at kontrollere din konto.");
        f1026c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Betalingen blev ikke oprettet. Dit loft for overførsel af penge er nået. Gå til vores websted for at kontrollere din konto.");
        f1026c.put("AUTH_RC_RISK_FAILURE", "Afvist på grund af risiko.");
        f1026c.put("AUTH_RC_OFAC_BLOCKED_IP", "Klienten er ikke godkendt.");
        f1026c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Klienten er ikke godkendt.");
        f1026c.put("invalid_user", "Forkert brugernavn/adgangskode. Prøv igen.");
        f1026c.put("locked_user", "Din PayPal-konto er blevet midlertidigt låst. Prøv igen senere, eller gå til www.paypal.com for straks at låse din PayPal-konto op.");
        f1026c.put("max_attempts_exceeded", "Du har forsøgt at logge på din konto for mange gange. Prøv igen senere.");
        f1026c.put("invalid_request", "Der opstod en fejl.");
        f1026c.put("unauthorized_client", "Anmodningen blev ikke godkendt.");
        f1026c.put("access_denied", "Anmodningen blev ikke godkendt.");
        f1026c.put("unsupported_response_type", "Der opstod en fejl.");
        f1026c.put("invalid_scope", "Anmodningen blev ikke godkendt.");
        f1026c.put("server_error", "Systemfejl. Prøv igen senere.");
        f1026c.put("temporarily_unavailable", "Systemfejl. Prøv igen senere.");
        f1026c.put("stepup_required", "Du kan ikke logge på i øjeblikket. Prøv igen senere, eller gå til www.paypal.dk for at løse eventuelle sikkerhedsproblemer med din PayPal-konto.");
    }

    public final String mo2147a() {
        return "da";
    }

    public final /* synthetic */ String mo2148a(Enum enumR, String str) {
        fw fwVar = (fw) enumR;
        String str2 = fwVar.toString() + "|" + str;
        return f1025b.containsKey(str2) ? (String) f1025b.get(str2) : (String) f1024a.get(fwVar);
    }

    public final String mo2149a(String str) {
        return (String) f1026c.get(str);
    }
}
