package com.paypal.android.sdk;

import com.payu.custombrowser.util.CBConstant;
import java.util.HashMap;
import java.util.Map;

public final class C0919x implements C0446h {
    private static final Map f1087a = new HashMap();
    private static final Map f1088b = new HashMap();
    private static final Map f1089c = new HashMap();

    public C0919x() {
        f1087a.put(fw.AGREE_AND_PAY, "Godta og betal");
        f1087a.put(fw.AND_OTHER_FUNDING_SOURCES, "og andre");
        f1087a.put(fw.AUTHENTICATING, "Godkjenner");
        f1087a.put(fw.BACK_BUTTON, "Tilbake");
        f1087a.put(fw.BACKUP_FUNDING_SOURCE, "Reserve");
        f1087a.put(fw.CANCEL, "Avbryt");
        f1087a.put(fw.CARDTYPE_AMERICANEXPRESS, "American Express");
        f1087a.put(fw.CARDTYPE_CARTAAURA, "Carta Aura");
        f1087a.put(fw.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f1087a.put(fw.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f1087a.put(fw.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f1087a.put(fw.CARDTYPE_COFINOGA, "Cofinoga");
        f1087a.put(fw.CARDTYPE_DELTA, "Delta");
        f1087a.put(fw.CARDTYPE_DISCOVER, "Discover");
        f1087a.put(fw.CARDTYPE_ELECTRON, "Electron");
        f1087a.put(fw.CARDTYPE_JCB, "JCB");
        f1087a.put(fw.CARDTYPE_MAESTRO, "Maestro");
        f1087a.put(fw.CARDTYPE_MASTERCARD, "MasterCard");
        f1087a.put(fw.CARDTYPE_POSTEPAY, "Postepay");
        f1087a.put(fw.CARDTYPE_4ETOILES, "4 étoiles");
        f1087a.put(fw.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f1087a.put(fw.CARDTYPE_VISA, "Visa");
        f1087a.put(fw.CHANGE_PAYMENT_METHOD, "Endre betalingsmetode");
        f1087a.put(fw.CHECKING_ACCOUNT_FOR_INSTITUTION, "Brukskonto");
        f1087a.put(fw.CHECKING_DEVICE, "Kontrollerer denne enheten …");
        f1087a.put(fw.CLEAR_CREDIT_CARD_INFO, "Fjern kortopplysningene");
        f1087a.put(fw.CONFIRM, "Bekreft");
        f1087a.put(fw.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Er du sikker på at du vil fjerne kortopplysningene dine?");
        f1087a.put(fw.CONFIRM_CHARGE_CREDIT_CARD, "Belast kortet");
        f1087a.put(fw.CONFIRM_LOG_OUT, "Er du sikker på at du vil logge av PayPal?");
        f1087a.put(fw.CONFIRM_SEND_PAYMENT, "Betal");
        f1087a.put(fw.CONSENT_AGREEMENT_AGREE, "Godta");
        f1087a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Opprettelsesdato for kontoen");
        f1087a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Kontostatus");
        f1087a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Kontotype");
        f1087a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Adresse");
        f1087a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Aldersgruppe");
        f1087a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Fødselsdato");
        f1087a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "E-postadresse");
        f1087a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Fullt navn");
        f1087a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Kjønn");
        f1087a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Språk");
        f1087a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Norsk, Norge");
        f1087a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefon");
        f1087a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Tidssone");
        f1087a.put(fw.CONSENT_AGREEMENT_ATTRIBUTES, "Del følgende: %s.");
        f1087a.put(fw.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Bruk sømløs-kassen.");
        f1087a.put(fw.CONSENT_AGREEMENT_INTRO, "%s ber om at du:");
        f1087a.put(fw.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Del <a href='%1$s'>betalingsmetodene</a> som er tilknyttet PayPal-kontoen din.");
        f1087a.put(fw.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Aktiver visning av finansieringskilder slik at du kan velge en.");
        f1087a.put(fw.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Godkjenn betalinger</a> for fremtidige kjøp hos %2$s via PayPal. Du ber PayPal om å betale alle summer som %3$s ber om.");
        f1087a.put(fw.CONSENT_AGREEMENT_LOYALTY_CARD, "Tillater at de legger til og administrerer et fordelskort i PayPal-lommeboken din.");
        f1087a.put(fw.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Godtar %1$s sine <a href='%2$s'>retningslinjer for personvern</a> og <a href='%3$s'>brukeravtale</a>.");
        f1087a.put(fw.CONSENT_AGREEMENT_REQUEST_MONEY, "Gi vedkommende tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f1087a.put(fw.CONSENT_AGREEMENT_SEND_MONEY, "Gi vedkommende tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f1087a.put(fw.CONSENT_AGREEMENT_TITLE, "Godta");
        f1087a.put(fw.EMAIL, "E-postadresse");
        f1087a.put(fw.ENVIRONMENT_MOCK_DATA, "Eksempeldata");
        f1087a.put(fw.ENVIRONMENT_SANDBOX, "Sandbox");
        f1087a.put(fw.EXPIRES_ON_DATE, "Utløper");
        f1087a.put(fw.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingsmetodene dine som er tilgjengelige for bruk.</p>");
        f1087a.put(fw.FORGOT_PASSWORD, "Har du glemt passordet?");
        f1087a.put(fw.FROM_ACCOUNT, "Fra");
        f1087a.put(fw.FUTURE_PAYMENT_METHOD_QUESTION, "Hvordan vil du finansiere fremtidige betalinger til %1$s er?");
        f1087a.put(fw.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>Den standard finansieringskilden din brukes til å utføre fremtidige PayPal-betalinger for denne forhandleren.</p><p>Hvis du vil avbryte denne avtalen, logger du på PayPal-kontoen, går til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Regelmessig betaling-delen av <a href='%s'>PayPals brukeravtale</a> er gjeldende.</p><p>For å kontrollere at betalinger fungerer med PayPal-kontoen din, kan denne appen simulere en liten prøvetransaksjonen, men ingen penger overføres.</p>");
        f1087a.put(fw.INTERNAL_ERROR, "Intern feil");
        f1087a.put(fw.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Ved å klikke på knappen nedenfor, godtar jeg vilkårene i <a href='%1$s'>PayPals brukeravtale</a> og jeg erklærer samtidig at jeg overholder japanske lover og forskrifter, herunder sanksjonsbestemmelser om betalinger til Nord-Korea og Iran, i tråd med japansk <a href='%2$s'>lovgivning om handel med utenlandske produkter og valuta</a>, for å fullføre transaksjonen.</p>");
        f1087a.put(fw.LOG_IN, "Logg på");
        f1087a.put(fw.LOG_IN_TO_PAYPAL, "Logg på med PayPal");
        f1087a.put(fw.LOG_OUT_BUTTON, "Logg ut");
        f1087a.put(fw.LOG_OUT, "Logg ut");
        f1087a.put(fw.OK, "OK");
        f1087a.put(fw.PASSWORD, "Passord");
        f1087a.put(fw.PAY_AFTER_DELIVERY, "Betal etter levering");
        f1087a.put(fw.PAY_WITH, "Betal med");
        f1087a.put(fw.PAY_WITH_CARD, "Betal med kort");
        f1087a.put(fw.PAYPAL_BALANCE, "PayPal-saldo");
        f1087a.put(fw.PAYPAL_CREDIT, "PayPal Credit");
        f1087a.put(fw.PHONE, "Telefonnummer");
        f1087a.put(fw.PIN, "PIN-kode");
        f1087a.put(fw.PREFERRED_PAYMENT_METHOD, "Foretrukket betalingsmetode");
        f1087a.put(fw.PRIVACY, "PayPal beskytter <a href='%s'>personvern</a>-opplysningene dine og den økonomiske informasjonen din.");
        f1087a.put(fw.PROCESSING, "Behandler");
        f1087a.put(fw.REMEMBER_CARD, "Husk kortet");
        f1087a.put(fw.REQUEST_MONEY, "Pengeforespørsel");
        f1087a.put(fw.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        f1087a.put(fw.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Sparekonto");
        f1087a.put(fw.SEND_MONEY, "Betal/overfør");
        f1087a.put(fw.SERVER_PROBLEM, "Det var et kommunikasjonsproblem med PayPal-serverne. Prøv på nytt.");
        f1087a.put(fw.SESSION_EXPIRED_MESSAGE, "Logg deg på PayPal på nytt.");
        f1087a.put(fw.SESSION_EXPIRED_TITLE, "Økten er utløpt");
        f1087a.put(fw.SHIPPING_ADDRESS, "Leveringsadresse");
        f1087a.put(fw.SIGN_UP, "Ny på PayPal? Opprett konto");
        f1087a.put(fw.STAY_LOGGED_IN, "Forbli pålogget");
        f1087a.put(fw.SYSTEM_ERROR_WITH_CODE, "Systemfeil (%s). Prøv på nytt senere.");
        f1087a.put(fw.TRY_AGAIN, "Prøv på nytt");
        f1087a.put(fw.TWO_FA_REQUIRED_ERROR, "Kan ikke logge på, fordi påloggingen til kontoen din har godkjenning med to faktorer.");
        f1087a.put(fw.TWO_FACTOR_AUTH_TITLE, "Sikkerhetskode");
        f1087a.put(fw.TWO_FACTOR_AUTH_SUBTITLE, "Send en tekstmelding til telefonen din. Den 6-sifrede koden du mottar, er gyldig i 5 minutter.");
        f1087a.put(fw.TWO_FACTOR_AUTH_SENDING_DIALOG, "Sender meldingen");
        f1087a.put(fw.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Oppgi den 6-sifrede sikkerhetskoden");
        f1087a.put(fw.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Ditt mobilnummer");
        f1087a.put(fw.TWO_FACTOR_AUTH_SEND_SMS, "Send melding");
        f1087a.put(fw.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Send meldingen på nytt");
        f1087a.put(fw.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Kan ikke logge på, fordi påloggingen til kontoen din har godkjenning med to faktorer. Gå til PayPals nettsted for å aktivere sikkerhetsnøkkelen din.");
        f1087a.put(fw.UNAUTHORIZED_DEVICE_MESSAGE, "Betaling fra denne enheten er ikke tillatt.");
        f1087a.put(fw.UNAUTHORIZED_DEVICE_TITLE, "Uautorisert enhet");
        f1087a.put(fw.UNAUTHORIZED_MERCHANT_MESSAGE, "Betalinger til denne forhandleren er ikke tillatt (ugyldig bruker-id).");
        f1087a.put(fw.UNAUTHORIZED_MERCHANT_TITLE, "Ugyldig forhandler");
        f1087a.put(fw.UNEXPECTED_PAYMENT_FLOW, "Det oppsto et problem ved behandlingen av betalingen. Prøv på nytt.");
        f1087a.put(fw.UNKNOWN_FUNDING_SOURCE, "Ukjent betalingsmetode");
        f1087a.put(fw.WE_ARE_SORRY, "Vi beklager");
        f1087a.put(fw.YOUR_ORDER, "Din bestilling");
        f1087a.put(fw.ANDROID_OS_TOO_OLD, "Denne enheten kan ikke kommunisere med PayPal fordi androidversjonen er for gammel. Oppgrader til en nyere androidversjon, eller forsøk med en nyere enhet.");
        f1087a.put(fw.CLEAR_CC_ALERT_TITLE, "Vil du fjerne kortet?");
        f1087a.put(fw.CONSENT_FAILED_ALERT_TITLE, "Godkjenningen mislyktes");
        f1087a.put(fw.CONNECTION_FAILED_TITLE, "Tilkobling mislykket");
        f1087a.put(fw.LOGIN_FAILED_ALERT_TITLE, "Pålogging mislyktes");
        f1087a.put(fw.LOGIN_WITH_EMAIL, "Logg på med passord");
        f1087a.put(fw.LOGIN_WITH_PHONE, "Logg på med PIN");
        f1087a.put(fw.ONE_MOMENT, "Et øyeblikk …");
        f1087a.put(fw.PAY_FAILED_ALERT_TITLE, "Betaling mislyktes");
        f1087a.put(fw.SCAN_CARD_ICON_DESCRIPTION, "Skann");
        f1087a.put(fw.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Feil sikkerhetskode. Prøv på nytt.");
        f1087a.put(fw.VIA_LABEL, "via");
        f1087a.put(fw.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "Systemfeil. Prøv på nytt senere.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Del informasjon om <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Del informasjon om <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Del informasjon om <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Del informasjon om <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Del informasjon om <a href='%1$s'>betalingsmetodene</a> som er tilknyttet PayPal-kontoen din.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Del informasjon med dem om <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Del <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Del <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Del informasjon om <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Del informasjon om <a href='%1$s'>betalingsmetodene</a> som er tilknyttet PayPal-kontoen din.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Del informasjon om <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Del informasjon om <a href='%1$s'>betalingsmetodene</a> som er tilknyttet PayPal-kontoen din.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Godkjenn betalinger</a> for fremtidige kjøp hos %2$s via PayPal. Du ber PayPal om å betale alle summer som %3$s ber om.</p><p>Du finner mer informasjon i <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPals avtale om regelmessige betalinger og fakturering</a>.</p>");
        f1088b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Godkjenn betalinger</a> for fremtidige kjøp hos %2$s via PayPal. Du ber PayPal om å betale alle summer som %3$s ber om.</p><p>Du finner mer informasjon i <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPals avtale om regelmessige betalinger og fakturering</a>.</p>");
        f1088b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>Godkjenn betalinger</a> for fremtidige kjøp via PayPal. Du gir PayPal din godkjenning, og ber oss om å betale alle beløp.");
        f1088b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>Godkjenn betalinger</a> for fremtidige kjøp via PayPal. Du gir PayPal din godkjenning, og ber oss om å betale alle beløp.");
        f1088b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>Godkjenn betalinger</a> for fremtidige kjøp via PayPal. Du gir PayPal din godkjenning, og ber oss om å betale alle beløp.");
        f1088b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Forhåndsgodkjenn fremtidige betalinger fra PayPal-kontoen din uten å logge på PayPal hver gang. <a href='%1$s'>Se ytterligere vilkår</a>, inkludert betalingsmetoder og hvordan du kan avbryte fremtidige betalinger.");
        f1088b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Gi %2$s tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Gi %2$s tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Gi %2$s tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Gi %2$s tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Gi %2$s tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Gi %2$s tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Gi %2$s tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Gi %2$s tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Gi %2$s tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Gi %2$s tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Gi %2$s tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Gi %2$s tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Gi %2$s tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f1088b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Gi %2$s tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun informasjon om hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun informasjon om hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun informasjon om hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        f1088b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Din standard betalingsmetode (PayPal-saldo, tilknyttet bankkonto eller betalingskort, i denne rekkefølgen) brukes til å betale for PayPal-kjøp. Vær oppmerksom på at hvis den standard betalingsmetoden din ikke har nok penger til å dekke kjøpet, kan banken eller kortleverandøren belaste deg et gebyr.</p><p>For å avbryte denne avtalen må du logge på PayPal-kontoen din og gå til <strong>Profil</strong>, så klikker du på <strong>Mine innstillinger</strong> og <strong>Endre</strong> ved siden av ‘Logg på med PayPal’.</p>");
        f1088b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>PayPal-saldoen din eller det primære betalingskortet ditt brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne avtalen, logger du på PayPal-kontoen, går til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p>");
        f1088b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Betalingsmetoden du angir som standard brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne avtalen, logger du på PayPal-kontoen, går til <strong>Profil</strong> &gt; <strong>Innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p>");
        f1088b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>Den standard finansieringskilden din brukes til å utføre fremtidige PayPal-betalinger hos denne forhandleren.</p><p>Hvis du vil avslutte denne avtalen, logger du på PayPal-kontoen din, går til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Regelmessig betaling-delen av <a href='%s'>PayPals brukeravtale</a> er gjeldende.</p><p>For å kontrollere at betalinger fungerer med PayPal-kontoen din, kan denne appen simulere en liten prøvetransaksjonen, men ingen penger overføres.</p>");
        f1088b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Betalingsmetoden du angir som standard brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne godkjenningen, logger du på PayPal-kontoen din, går til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se ‘Forhåndsgodkjente betalinger’-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        f1088b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Betalingsmetoden du angir som standard brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne godkjenningen, logger du på PayPal-kontoen din, går til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se ‘Forhåndsgodkjente betalinger’-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        f1088b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>PayPal-saldoen din eller det primære betalingskortet ditt brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne avtalen, logger du på PayPal-kontoen, går til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p>");
        f1088b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Betalingsmetoden du angir som standard brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne godkjenningen, logger du på PayPal-kontoen din, går til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se ‘Forhåndsgodkjente betalinger’-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        f1088b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Betalingsmetoden du angir som standard brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne godkjenningen, logger du på PayPal-kontoen din, går til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se ‘Forhåndsgodkjente betalinger’-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        f1088b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Betalingsmetoden du angir som standard brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne godkjenningen, logger du på PayPal-kontoen din, går til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se ‘Forhåndsgodkjente betalinger’-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        f1088b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>Vi forsøker først å betale med PayPal-saldoen din. Hvis det ikke er nok penger på den, forsøker vi å bruke bankkontoen din, PayPal Credit, betalingskort og/eller eCheck, i den viste rekkefølgen.</p><p>Hvis du vil avbryte denne avtalen, går du til www.paypal.com <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Det kan være nødvendig med en liten betalingsgodkjenning for å kontrollere at PayPal-kontoen din kan belastes i fremtiden. Godkjenningen blir avbrutt, og du belastes ikke.</p>");
        f1088b.put("LOG_IN_TO_PAYPAL|AU", "Logg på med PayPal");
        f1088b.put("LOG_IN_TO_PAYPAL|GB", "Logg på med PayPal");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din og klikker på tannhjulikonet. Gå til <strong>Sikkerhet</strong>, velg <strong>Logg på med PayPal</strong> og fjern denne partneren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene, og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din og klikker på tannhjulikonet. Gå til <strong>Sikkerhet</strong>, velg <strong>Logg på med PayPal</strong> og fjern denne partneren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din og klikker på tannhjulikonet. Gå til <strong>Sikkerhet</strong>, velg <strong>Logg på med PayPal</strong> og fjern denne partneren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, klikker på tannhjulikonet øverst til høyre, velger <strong>Sikkerhet</strong>, <strong>Logg på med PayPal</strong> og fjerner forhandleren. Hvis du fortsatt bruker den tidligere versjonen av nettstedet, går du til <strong>Min profil</strong>, velger <strong>Mine kontoinnstillinger</strong>, <strong>Logg på med PayPal</strong> og fjerner forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Profil</strong>-innstillingene, <strong>Logg på med PayPal</strong> og fjerner denne partneren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.it, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene, og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene, og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.ru, klikker på tannhjulikonet øverst til høyre, velger <strong>Sikkerhet</strong>-fanen og fjerner denne partneren under alternativet <strong>Logg på med PayPal</strong>.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.tr, klikker på tannhjulikonet øverst til høyre, velger <strong>Sikkerhet</strong>-fanen og fjerner denne partneren under alternativet <strong>Logg på med PayPal</strong>.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1088b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f1089c.put("AMOUNT_MISMATCH", "Totalbeløpet for varene i handlekurven samsvarer ikke med kjøpesummen.");
        f1089c.put("AUTHORIZATION_ALREADY_COMPLETED", "Denne godkjenningen er allerede fullført.");
        f1089c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Godkjenningen er i et stadium som ikke kan bli annullert.");
        f1089c.put("AUTHORIZATION_EXPIRED", "Godkjenning utløpt.");
        f1089c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Den forespurte godkjennings-IDen finnes ikke.");
        f1089c.put("AUTHORIZATION_VOIDED", "Godkjenningen din er annullert.");
        f1089c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Kan bare godkjenne den opprinnelige godkjenningen, ikke en ny godkjenning.");
        f1089c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Ny godkjenning er ikke tillatt innenfor prøveperioden.");
        f1089c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Beløpet overskrider den tillatte grensen.");
        f1089c.put("CARD_TOKEN_PAYER_MISMATCH", "Får ikke tilgang til lagret kortinformasjonen.");
        f1089c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Kortopplysningene er ugyldige. Vi ber deg korrigere og sende inn på nytt.");
        f1089c.put("CREDIT_CARD_REFUSED", "Kortet ble avvist.");
        f1089c.put("CURRENCY_MISMATCH", "Valuta for innhentingen må være lik valutaen for godkjenning.");
        f1089c.put("CURRENCY_NOT_ALLOWED", "Denne valutaen støttes for øyeblikket ikke av PayPal.");
        f1089c.put("DATA_RETRIEVAL", "Systemfeil. Prøv på nytt senere.");
        f1089c.put("DUPLICATE_REQUEST_ID", "Systemfeil. Prøv på nytt senere.");
        f1089c.put("EXPIRED_CREDIT_CARD", "Kortet er utløpt");
        f1089c.put("EXPIRED_CREDIT_CARD_TOKEN", "Informasjonen for dette kortet er ikke lenger registrert.\nVennligst send på nytt.");
        f1089c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Funksjonen støttes ikke for denne forhandleren.");
        f1089c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Denne transaksjonen er allerede delvis refundert.");
        f1089c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Øyeblikkelig betaling støttes ikke for den forespurte tjenesten.");
        f1089c.put("INSTRUMENT_DECLINED", "Den betalingsmetoden du valgte ble ikke godtatt. Velg en annen betalingsmetode.");
        f1089c.put("INSUFFICIENT_FUNDS", "Kjøperen kan ikke betale – ikke nok penger.");
        f1089c.put("INTERNAL_SERVICE_ERROR", "Systemfeil. Prøv på nytt senere.");
        f1089c.put("INVALID_ACCOUNT_NUMBER", "Det kontonummeret finnes ikke.");
        f1089c.put("INVALID_ARGUMENT", "Transaksjon avvist på grunn av et ugyldig parameter");
        f1089c.put("INVALID_CITY_STATE_ZIP", "Ugyldig kombinasjon for poststed/land/postnummerkombinasjon.");
        f1089c.put("INVALID_FACILITATOR_CONFIGURATION", "Denne transaksjonen kan ikke behandles på grunn av en ugyldig systeminnretningskonfigurasjon.");
        f1089c.put("INVALID_PAYER_ID", "Systemfeil (ugyldig betaler-id). Prøv på nytt senere.");
        f1089c.put("INVALID_RESOURCE_ID", "Systemfeil. Prøv på nytt senere.");
        f1089c.put("PAYEE_ACCOUNT_INVALID", "Kontoen til betalingsmottakeren din har ikke en bekreftet e-post.");
        f1089c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Selgeren kan for øyeblikket ikke motta betalinger.");
        f1089c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Kontoen til betalingsmottakeren din har ikke en bekreftet e-post.");
        f1089c.put("PAYEE_ACCOUNT_RESTRICTED", "Selgeren kan for øyeblikket ikke motta betalinger.");
        f1089c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Kontoen din er låst eller avsluttet.");
        f1089c.put("PAYER_ACCOUNT_RESTRICTED", "Kontoen din er begrenset.");
        f1089c.put("PAYER_CANNOT_PAY", "Du kan ikke betale for denne transaksjonen med PayPal.");
        f1089c.put("PAYER_EMPTY_BILLING_ADDRESS", "Det er nødvendig med en faktureringsadresse ved betalingskorttransaksjoner utenfor PayPal.");
        f1089c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Får ikke tilgang til lagret kortinformasjonen.");
        f1089c.put("PAYMENT_APPROVAL_EXPIRED", "Betalingsgodkjenningen er utløpt.");
        f1089c.put("PAYMENT_EXPIRED", "Betalingen er utløpt.");
        f1089c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Betaleren har ikke godtatt betalingen.");
        f1089c.put("PAYMENT_REQUEST_ID_INVALID", "PayPal-forespørselen er ugyldig. Prøv på nytt senere.");
        f1089c.put("PAYMENT_STATE_INVALID", "Denne forespørselen er ugyldig på grunn av gjeldende status for betalingen.");
        f1089c.put("PERMISSION_DENIED", "Ingen tillatelse til den forespurte operasjonen.");
        f1089c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Den forespurte refusjonen overskrider beløpet for den opprinnelige transaksjonen.");
        f1089c.put("REFUND_TIME_LIMIT_EXCEEDED", "Denne transaksjonen er for gammel til at den kan refunderes.");
        f1089c.put("REQUIRED_SCOPE_MISSING", "Systemfeil. Prøv på nytt senere.");
        f1089c.put("TOO_MANY_REAUTHORIZATIONS", "Ingen flere nye godkjenninger er tillatt for denne godkjenningen.");
        f1089c.put("TRANSACTION_ALREADY_REFUNDED", "Denne transaksjonen er allerede refundert.");
        f1089c.put("TRANSACTION_LIMIT_EXCEEDED", "Beløpet overskrider den tillatte grensen.");
        f1089c.put("TRANSACTION_REFUSED", "Transaksjonen ble avvist.");
        f1089c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Transaksjonen ble avvist.");
        f1089c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Forhandlerprofilen er innstilt til å automatisk tilbakevise visse transaksjoner.");
        f1089c.put("UNKNOWN_ERROR", "Systemfeil. Prøv på nytt senere.");
        f1089c.put("UNSUPPORTED_PAYEE_COUNTRY", "Landet støttes ikke.");
        f1089c.put("VALIDATION_ERROR", "Betalingsinformasjonen er ugyldig. Vi ber deg korrigere og sende inn på nytt.");
        f1089c.put("ORDER_ALREADY_COMPLETED", "Bestillingen er allerede annullert, utløpt eller fullført.");
        f1089c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Maksimalt antall tillatte godkjenninger for bestillingen er nådd.");
        f1089c.put("ORDER_VOIDED", "Bestillingen er blitt annullert.");
        f1089c.put("ORDER_CANNOT_BE_VOIDED", "Det er ikke mulig å annullere bestillingen i denne delen av prosessen.");
        f1089c.put("INVALID_EXPERIENCE_PROFILE_ID", "Systemfeil. Prøv på nytt senere.");
        f1089c.put("UNAUTHORIZED_PAYMENT", "Forhandleren godtar ikke betalinger av denne typen.");
        f1089c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Valuta ikke støttet for korttypen.");
        f1089c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Korttypen støttes ikke.");
        f1089c.put("ADDRESS_ADDITION_ERROR", "Det oppstod et problem i løpet av prosessen med å legge til en forsendelsesadresse i PayPal-kontoen.");
        f1089c.put("DUPLICATE_TRANSACTION", "Duplikattransaksjon.");
        f1089c.put("INVALID_SHIPPING_ADDRESS", "Den oppgitte leveringsadressen er ikke gyldig.");
        f1089c.put("PAYMENT_CREATION_ERROR", "Det oppsto et problem med opprettelsen av denne betalingen. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        f1089c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Det oppsto et problem med opprettelsen av denne betalingen – kortet ditt er utløpt. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        f1089c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Det oppsto et problem med opprettelsen av denne betalingen – direktebetaling kreves, f.eks. med et kredittkort. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        f1089c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Det oppsto et problem med opprettelsen av denne betalingen – kortet må bekreftes. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        f1089c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Det oppsto et problem med opprettelsen av denne betalingen – denne appen krever at kontoen din inneholder et telefonnummer. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        f1089c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Det oppsto et problem med opprettelsen av denne betalingen – kontoen må ha en gyldig finansieringskilde, f.eks. en bankkonto eller et betalingskort. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        f1089c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Det oppsto et problem med opprettelsen av denne betalingen – saldoen din er i minus. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        f1089c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Det oppsto et problem med opprettelsen av denne betalingen – sendegrensen din er nådd. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        f1089c.put("AUTH_RC_RISK_FAILURE", "Avvist grunnet risiko.");
        f1089c.put("AUTH_RC_OFAC_BLOCKED_IP", "Klienten er ikke godkjent.");
        f1089c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Klienten er ikke godkjent.");
        f1089c.put("invalid_user", "Feil brukernavn/passord. Prøv på nytt.");
        f1089c.put("locked_user", "PayPal-kontoen din er midlertidig sperret. Prøv på nytt senere, eller gå til www.paypal.com for å låse opp PayPal-kontoen din med en gang.");
        f1089c.put("max_attempts_exceeded", "For mange mislykkede påloggingsforsøk. Prøv på nytt senere.");
        f1089c.put("invalid_request", "Det har oppstått en feil.");
        f1089c.put("unauthorized_client", "Ikke godkjent forespørsel.");
        f1089c.put("access_denied", "Ikke godkjent forespørsel.");
        f1089c.put("unsupported_response_type", "Det har oppstått en feil.");
        f1089c.put("invalid_scope", "Ikke godkjent forespørsel.");
        f1089c.put("server_error", "Systemfeil. Prøv på nytt senere.");
        f1089c.put("temporarily_unavailable", "Systemfeil. Prøv på nytt senere.");
        f1089c.put("stepup_required", "Det er ikke mulig å logge på akkurat nå. Prøv på nytt senere, eller gå til www.paypal.com for å løse eventuelle sikkerhetsproblemer med kontoen din.");
    }

    public final String mo2147a() {
        return CBConstant.NB;
    }

    public final /* synthetic */ String mo2148a(Enum enumR, String str) {
        fw fwVar = (fw) enumR;
        String str2 = fwVar.toString() + "|" + str;
        return f1088b.containsKey(str2) ? (String) f1088b.get(str2) : (String) f1087a.get(fwVar);
    }

    public final String mo2149a(String str) {
        return (String) f1089c.get(str);
    }
}
