package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

public final class C0914r implements C0446h {
    private static final Map f1072a = new HashMap();
    private static final Map f1073b = new HashMap();
    private static final Map f1074c = new HashMap();

    public C0914r() {
        f1072a.put(fw.AGREE_AND_PAY, "הסכם ושלם");
        f1072a.put(fw.AND_OTHER_FUNDING_SOURCES, "ואחרים");
        f1072a.put(fw.AUTHENTICATING, "אימות");
        f1072a.put(fw.BACK_BUTTON, "חזרה");
        f1072a.put(fw.BACKUP_FUNDING_SOURCE, "גיבוי");
        f1072a.put(fw.CANCEL, "ביטול");
        f1072a.put(fw.CARDTYPE_AMERICANEXPRESS, "אמריקן אקספרס");
        f1072a.put(fw.CARDTYPE_CARTAAURA, "Carta Aura‏");
        f1072a.put(fw.CARDTYPE_CARTEAURORE, "Carte Aurore‏");
        f1072a.put(fw.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal‏");
        f1072a.put(fw.CARDTYPE_CARTEBLEUE, "Carte Bancaire‏");
        f1072a.put(fw.CARDTYPE_COFINOGA, "Cofinoga‏");
        f1072a.put(fw.CARDTYPE_DELTA, "Delta‏");
        f1072a.put(fw.CARDTYPE_DISCOVER, "Discover‏");
        f1072a.put(fw.CARDTYPE_ELECTRON, "Electron‏");
        f1072a.put(fw.CARDTYPE_JCB, "JCB‏");
        f1072a.put(fw.CARDTYPE_MAESTRO, "Maestro‏");
        f1072a.put(fw.CARDTYPE_MASTERCARD, "מאסטרקארד");
        f1072a.put(fw.CARDTYPE_POSTEPAY, "Postepay‏");
        f1072a.put(fw.CARDTYPE_4ETOILES, "‎4 étoiles‎‏");
        f1072a.put(fw.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora‏");
        f1072a.put(fw.CARDTYPE_VISA, "ויזה");
        f1072a.put(fw.CHANGE_PAYMENT_METHOD, "שנה שיטת תשלום");
        f1072a.put(fw.CHECKING_ACCOUNT_FOR_INSTITUTION, "עו״ש");
        f1072a.put(fw.CHECKING_DEVICE, "בודק מכשיר זה…");
        f1072a.put(fw.CLEAR_CREDIT_CARD_INFO, "נקה פרטי כרטיס");
        f1072a.put(fw.CONFIRM, "אשר");
        f1072a.put(fw.CONFIRM_CLEAR_CREDIT_CARD_INFO, "האם אתה בטוח שאתה רוצה להסיר את פרטי הכרטיס שלך?");
        f1072a.put(fw.CONFIRM_CHARGE_CREDIT_CARD, "חייב כרטיס");
        f1072a.put(fw.CONFIRM_LOG_OUT, "האם אתה בטוח שאתה רוצה לצאת מ-PayPal‏?");
        f1072a.put(fw.CONFIRM_SEND_PAYMENT, "שלם");
        f1072a.put(fw.CONSENT_AGREEMENT_AGREE, "מסכים");
        f1072a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "תאריך פתיחת החשבון");
        f1072a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "מצב חשבון");
        f1072a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "סוג חשבון");
        f1072a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "כתובת");
        f1072a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "טווח גילים");
        f1072a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "תאריך לידה");
        f1072a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "כתובת אימייל");
        f1072a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "שם מלא");
        f1072a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "מין");
        f1072a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "שפה");
        f1072a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "אזור");
        f1072a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "טלפון");
        f1072a.put(fw.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "אזור זמן");
        f1072a.put(fw.CONSENT_AGREEMENT_ATTRIBUTES, "שתף את הפרטים הבאים: ‎%s‏.");
        f1072a.put(fw.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "השתמש ב-Express Checkout‏.");
        f1072a.put(fw.CONSENT_AGREEMENT_INTRO, "%s מבקש כי:");
        f1072a.put(fw.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "שתף את <a href='%1$s'>שיטות התשלום</a> המקושרות לחשבון ה-PayPal שלך.");
        f1072a.put(fw.CONSENT_AGREEMENT_FUNDING_OPTIONS, "הפעל תצוגה של האפשרויות הכספיות שלך שתאפשר לך לבחור.");
        f1072a.put(fw.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>אשר חיובים</a> עבור קניות עתידיות אצל ‎%2$s באמצעות PayPal‏. הורית ל-PayPal לשלם את כל הסכומים ש-‎%3$s מבקש.");
        f1072a.put(fw.CONSENT_AGREEMENT_LOYALTY_CARD, "תאפשר לו להוסיף ולנהל את כרטיס המועדון שלו ב‘ארנק‘ שבחשבון ה-PayPal שלך.");
        f1072a.put(fw.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "תסכים ל<a href='%2$s'>מדיניות הפרטיות</a> ו<a href='%3$s'>הסכם המשתמש</a> של %1$s‏.");
        f1072a.put(fw.CONSENT_AGREEMENT_REQUEST_MONEY, "תאפשר לו <a href='%1$s'>לבקש תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        f1072a.put(fw.CONSENT_AGREEMENT_SEND_MONEY, "תאפשר לו <a href='%1$s'>לשלוח תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        f1072a.put(fw.CONSENT_AGREEMENT_TITLE, "הסכמה");
        f1072a.put(fw.EMAIL, "אימייל");
        f1072a.put(fw.ENVIRONMENT_MOCK_DATA, "פרטים מדומים");
        f1072a.put(fw.ENVIRONMENT_SANDBOX, "‏Sandbox");
        f1072a.put(fw.EXPIRES_ON_DATE, "תאריך תפוגה");
        f1072a.put(fw.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>דרכי תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו משיטות התשלום שלך זמינות לשימוש.</p>");
        f1072a.put(fw.FORGOT_PASSWORD, "שכחת את הסיסמה?");
        f1072a.put(fw.FROM_ACCOUNT, "מ-");
        f1072a.put(fw.FUTURE_PAYMENT_METHOD_QUESTION, "כיצד תרצה לשלם עבור תשלומים עתידיים ל-%1$s‏?");
        f1072a.put(fw.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>הסכם תשלום עתידי</strong></h1><p>ברירת המחדל לשיטת התשלום שלך תשמש עבור תשלומים עתידיים באמצעות PayPal אצל בעל עסק זה.</p><p>כדי לבטל הסכם זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>ההגדרות שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p><p>המקטע ‘הוראת קבע‘ של <a href='%s'>הסכם המשתמש של PayPal</a> יחול.</p><p>כדי לוודא שהתשלומים שלך יעבדו עם חשבון ה-PayPal שלך, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר כסף.</p>");
        f1072a.put(fw.INTERNAL_ERROR, "שגיאה פנימית");
        f1072a.put(fw.JAPANESE_COMPLIANCE_AGREEMENT, "<p>על-ידי לחיצה על הלחצן למטה, אני מסכים בזאת לתנאי <a href='%1$s'>הסכם המשתמש של PayPal</a> ומצהיר שאני פועל בהתאם לחוקים ולתקנות ביפן, כולל סנקציות נגד תשלום לצפון קוריאה ואירן, בהתאם ל-<a href='%2$s'>Foreign Exchange and Foreign Trade Act</a>, להשלמת העסקה.</p>");
        f1072a.put(fw.LOG_IN, "כניסה");
        f1072a.put(fw.LOG_IN_TO_PAYPAL, "היכנס עם PayPal‏");
        f1072a.put(fw.LOG_OUT_BUTTON, "יציאה");
        f1072a.put(fw.LOG_OUT, "יציאה");
        f1072a.put(fw.OK, "אישור");
        f1072a.put(fw.PASSWORD, "סיסמה");
        f1072a.put(fw.PAY_AFTER_DELIVERY, "שלם לאחר המסירה");
        f1072a.put(fw.PAY_WITH, "שלם באמצעות");
        f1072a.put(fw.PAY_WITH_CARD, "שלם באמצעות כרטיס");
        f1072a.put(fw.PAYPAL_BALANCE, "יתרת חשבון ה-PayPal");
        f1072a.put(fw.PAYPAL_CREDIT, "PayPal Credit");
        f1072a.put(fw.PHONE, "טלפון");
        f1072a.put(fw.PIN, "קוד סודי");
        f1072a.put(fw.PREFERRED_PAYMENT_METHOD, "שיטת תשלום מועדפת");
        f1072a.put(fw.PRIVACY, "PayPal מגינה על ה<a href='%s'>פרטיות</a> והמידע הפיננסי שלך.");
        f1072a.put(fw.PROCESSING, "עיבוד");
        f1072a.put(fw.REMEMBER_CARD, "זכור כרטיס");
        f1072a.put(fw.REQUEST_MONEY, "בקש תשלום");
        f1072a.put(fw.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של השותף.</p>");
        f1072a.put(fw.SAVINGS_ACCOUNT_FOR_INSTITUTION, "חיסכון");
        f1072a.put(fw.SEND_MONEY, "שלח תשלום");
        f1072a.put(fw.SERVER_PROBLEM, "הייתה בעיה ביצירת קשר עם השרתים של PayPal‏. נסה שוב.");
        f1072a.put(fw.SESSION_EXPIRED_MESSAGE, "היכנס שוב ל-PayPal‏.");
        f1072a.put(fw.SESSION_EXPIRED_TITLE, "פג תוקף ההפעלה");
        f1072a.put(fw.SHIPPING_ADDRESS, "כתובת למשלוח");
        f1072a.put(fw.SIGN_UP, "חדש ב-PayPal‏? הירשם");
        f1072a.put(fw.STAY_LOGGED_IN, "הישאר מחובר");
        f1072a.put(fw.SYSTEM_ERROR_WITH_CODE, "שגיאת מערכת (%s‏). נסה שוב מאוחר יותר.");
        f1072a.put(fw.TRY_AGAIN, "נסה שוב");
        f1072a.put(fw.TWO_FA_REQUIRED_ERROR, "לא ניתן להיכנס לחשבון, משום שאימות בשני שלבים הופעל עבור החשבון שלך.");
        f1072a.put(fw.TWO_FACTOR_AUTH_TITLE, "קוד אבטחה");
        f1072a.put(fw.TWO_FACTOR_AUTH_SUBTITLE, "שלח הודעת טקסט לטלפון שלך. הקוד בן שש הספרות שתקבל יישאר בתוקף למשך 5 דקות.");
        f1072a.put(fw.TWO_FACTOR_AUTH_SENDING_DIALOG, "שולח טקסט");
        f1072a.put(fw.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "הזן את קוד האבטחה בן שש הספרות");
        f1072a.put(fw.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "מספר הטלפון הנייד שלך");
        f1072a.put(fw.TWO_FACTOR_AUTH_SEND_SMS, "שלח טקסט");
        f1072a.put(fw.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "שלח טקסט שוב");
        f1072a.put(fw.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "לא ניתן להיכנס לחשבון, משום שאימות בשני שלבים הופעל עבור החשבון שלך. בקר באתר PayPal כדי להפעיל את מפתח האבטחה שלך.");
        f1072a.put(fw.UNAUTHORIZED_DEVICE_MESSAGE, "לא ניתן לשלם ממכשיר זה.");
        f1072a.put(fw.UNAUTHORIZED_DEVICE_TITLE, "מכשיר בלתי-מורשה");
        f1072a.put(fw.UNAUTHORIZED_MERCHANT_MESSAGE, "לא ניתן לשלם לבעל עסק זה (מזהה לקוח בלתי-חוקי).");
        f1072a.put(fw.UNAUTHORIZED_MERCHANT_TITLE, "בעל עסק בלתי-חוקי");
        f1072a.put(fw.UNEXPECTED_PAYMENT_FLOW, "אירעה בעיה בעיבוד התשלום שלך. נסה שוב.");
        f1072a.put(fw.UNKNOWN_FUNDING_SOURCE, "מקור בלתי מזוהה");
        f1072a.put(fw.WE_ARE_SORRY, "מצטערים");
        f1072a.put(fw.YOUR_ORDER, "ההזמנה שלך");
        f1072a.put(fw.ANDROID_OS_TOO_OLD, "מכשיר זה לא יכול ליצור קשר עם PayPal משום שגירסה זו של אנדרואיד ישנה מדי. שדרג את גירסת האנדרואיד או נסה מכשיר חדש יותר.");
        f1072a.put(fw.CLEAR_CC_ALERT_TITLE, "להסיר את הכרטיס?");
        f1072a.put(fw.CONSENT_FAILED_ALERT_TITLE, "ההסכמה נכשלה");
        f1072a.put(fw.CONNECTION_FAILED_TITLE, "החיבור נכשל");
        f1072a.put(fw.LOGIN_FAILED_ALERT_TITLE, "הכניסה נכשלה");
        f1072a.put(fw.LOGIN_WITH_EMAIL, "היכנס באמצעות סיסמה");
        f1072a.put(fw.LOGIN_WITH_PHONE, "היכנס באמצעות קוד סודי");
        f1072a.put(fw.ONE_MOMENT, "המתן רגע אחד…");
        f1072a.put(fw.PAY_FAILED_ALERT_TITLE, "התשלום נכשל");
        f1072a.put(fw.SCAN_CARD_ICON_DESCRIPTION, "סריקה");
        f1072a.put(fw.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "קוד אבטחה שגוי. נסה שוב.");
        f1072a.put(fw.VIA_LABEL, "באמצעות");
        f1072a.put(fw.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "שגיאת מערכת. נסה שוב מאוחר יותר.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "שתף מידע על <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "שתף את המידע על <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "שתף מידע על <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "שתף מידע על <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "שתף מידע על <a href='%1$s'>שיטות התשלום</a> המקושרות לחשבון ה-PayPal שלך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "שתף איתם מידע על <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "שתף את <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "שתף את <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "שתף את המידע על <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "שתף מידע על <a href='%1$s'>שיטות התשלום</a> המקושרות לחשבון ה-PayPal שלך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "שתף את המידע על <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "שתף מידע על <a href='%1$s'>שיטות התשלום</a> המקושרות לחשבון ה-PayPal שלך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>אשר חיובים</a> עבור קניות עתידיות אצל ‎%2$s באמצעות PayPal‏. הורית ל-PayPal לשלם את כל הסכומים ש-‎%3$s מבקש.</p><p>לפרטים נוספים, עיין ב<a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>הסכם הוראות הקבע והחיוב של PayPal‏</a>.</p>");
        f1073b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>אשר חיובים</a> עבור קניות עתידיות אצל ‎%2$s באמצעות PayPal‏. הורית ל-PayPal לשלם את כל הסכומים ש-‎%3$s מבקש.</p><p>לפרטים נוספים, עיין ב<a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>הסכם הוראות הקבע והחיוב של PayPal‏</a>.</p>");
        f1073b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>אשר חיובים</a> עבור קניות עתידיות באמצעות PayPal‏. אתה מעניק ל-PayPal אישור לשלם את כל הסכומים.");
        f1073b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>אשר חיובים</a> עבור קניות עתידיות באמצעות PayPal‏. אתה מעניק ל-PayPal אישור לשלם את כל הסכומים.");
        f1073b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>אשר חיובים</a> עבור קניות עתידיות באמצעות PayPal‏. אתה מעניק ל-PayPal אישור לשלם את כל הסכומים.");
        f1073b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "אשר מראש תשלומים עתידיים מחשבון ה-PayPal שלך בלי להיכנס אל PayPal בכל פעם. <a href='%1$s'>ראה תנאים נוספים</a>, כולל שיטות תשלום וכיצד לבטל תשלומים עתידיים.");
        f1073b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "תאפשר ל-‎%2$s‎ <a href='%1$s'>לבקש תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "תאפשר ל-‎%2$s‎ <a href='%1$s'>לבקש תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "תאפשר ל-‎%2$s‎ <a href='%1$s'>לבקש תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "תאפשר ל-‎%2$s‎ <a href='%1$s'>לבקש תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "תאפשר ל-‎%2$s‎ <a href='%1$s'>לבקש תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "תאפשר ל-‎%2$s‎ <a href='%1$s'>לבקש תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "תאפשר ל-‎%2$s‎ <a href='%1$s'>לבקש תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "תאפשר ל-‎%2$s‎ <a href='%1$s'>לשלוח תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "תאפשר ל-‎%2$s‎ <a href='%1$s'>לשלוח תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "תאפשר ל-‎%2$s‎ <a href='%1$s'>לשלוח תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "תאפשר ל-‎%2$s‎ <a href='%1$s'>לשלוח תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "תאפשר ל-‎%2$s‎ <a href='%1$s'>לשלוח תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "תאפשר ל-‎%2$s‎ <a href='%1$s'>לשלוח תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        f1073b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "תאפשר ל-‎%2$s‎ <a href='%1$s'>לשלוח תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        f1073b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>הסכם תשלומים עתידיים</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר כסף.</p><p>ברירת המחדל לשיטת התשלום שלך (יתרת חשבון ה-PayPal שלך, חשבון בנק מקושר או כרטיס אשראי, בסדר הזה) תשמש לתשלום עבור הקניות באמצעות PayPal‏. שים לב, אם בברירת המחדל לשיטת התשלום שלך לא יהיה מספיק כסף לכיסוי הקנייה, הבנק שבו מתנהל חשבונך או ספק הכרטיס שלך עשוי לחייב אותך בעמלה.</p><p>כדי לבטל הסכם זה, היכנס לחשבון ה-PayPal שלך ועבור אל <strong>פרופיל</strong>, לאחר מכן לחץ על <strong>ההגדרות שלי</strong> ועל <strong>שינוי</strong> לצד ’היכנס עם PayPal‏‘.</p>");
        f1073b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>הסכם תשלום עתידי</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר כסף.</p><p>יתרת חשבון ה-PayPal שלך או כרטיס האשראי הראשי שלך ישמשו לתשלום עבור הקניות באמצעות PayPal‏.</p><p>כדי לבטל הסכם זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>ההגדרות שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p>");
        f1073b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>הסכם תשלום עתידי</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר תשלום.</p><p>ברירת המחדל לשיטת התשלום שלך תשמש לתשלום עבור הקניות באמצעות PayPal‏.</p><p>כדי לבטל הסכם זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>הגדרות</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p>");
        f1073b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>הסכם תשלום עתידי</strong></h1><p>ברירת המחדל לשיטת התשלום שלך תשמש עבור תשלומים עתידיים באמצעות PayPal אצל בעל עסק זה.</p><p>כדי לבטל הסכם זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>ההגדרות שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p><p>המקטע ‘הוראת קבע‘ של <a href='%s'>הסכם המשתמש של PayPal</a> יחול.</p><p>כדי לוודא שהתשלומים שלך יעבדו עם חשבון ה-PayPal שלך, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר כסף.</p>");
        f1073b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>אישור תשלום עתידי</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר תשלום.</p><p>ברירת המחדל לשיטת התשלום שלך תשמש לתשלום עבור הקניות באמצעות PayPal‏.</p><p>כדי לבטל אישור זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>הגדרות החשבון שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p><p>לפרטים נוספים, עיין במקטע ’תשלומים שאושרו מראש‘ ב<a href='%s'>הסכם המשתמש של PayPal‏</a>.</p>");
        f1073b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>אישור תשלום עתידי</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר תשלום.</p><p>ברירת המחדל לשיטת התשלום שלך תשמש לתשלום עבור הקניות באמצעות PayPal‏.</p><p>כדי לבטל אישור זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>הגדרות החשבון שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p><p>לפרטים נוספים, עיין במקטע ’תשלומים שאושרו מראש‘ ב<a href='%s'>הסכם המשתמש של PayPal‏</a>.</p>");
        f1073b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>הסכם תשלום עתידי</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר כסף.</p><p>יתרת חשבון ה-PayPal שלך או כרטיס האשראי הראשי שלך ישמשו לתשלום עבור הקניות באמצעות PayPal‏.</p><p>כדי לבטל הסכם זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>ההגדרות שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p>");
        f1073b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>אישור תשלום עתידי</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר תשלום.</p><p>ברירת המחדל לשיטת התשלום שלך תשמש לתשלום עבור הקניות באמצעות PayPal‏.</p><p>כדי לבטל אישור זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>הגדרות החשבון שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p><p>לפרטים נוספים, עיין במקטע ’תשלומים שאושרו מראש‘ ב<a href='%s'>הסכם המשתמש של PayPal‏</a>.</p>");
        f1073b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>אישור תשלום עתידי</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר תשלום.</p><p>ברירת המחדל לשיטת התשלום שלך תשמש לתשלום עבור הקניות באמצעות PayPal‏.</p><p>כדי לבטל אישור זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>הגדרות החשבון שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p><p>לפרטים נוספים, עיין במקטע ’תשלומים שאושרו מראש‘ ב<a href='%s'>הסכם המשתמש של PayPal‏</a>.</p>");
        f1073b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>אישור תשלום עתידי</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר תשלום.</p><p>ברירת המחדל לשיטת התשלום שלך תשמש לתשלום עבור הקניות באמצעות PayPal‏.</p><p>כדי לבטל אישור זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>הגדרות החשבון שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p><p>לפרטים נוספים, עיין במקטע ’תשלומים שאושרו מראש‘ ב<a href='%s'>הסכם המשתמש של PayPal‏</a>.</p>");
        f1073b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>הסכם תשלום עתידי</strong></h1><p>PayPal תשתמש תחילה ביתרת חשבון ה-PayPal שלך כדי לשלם עבור הקנייה שלך. במקרה שהיתרה אינה מכסה את הסכום המלא, יעשה שימוש בחשבון הבנק, PayPal Credit, כרטיס האשראי ו/או המחאה אלקטרונית שלך, בסדר הזה.</p><p>כדי לבטל הסכם זה, עבור אל www.paypal.co.il <strong>פרופיל</strong> &gt; <strong>ההגדרות שלי</strong> &gt; <strong>היכנס עם PayPal</strong> ולאחר מכן הסר בעל עסק זה מהרשימה.</p><p>ייתכן שיידרש אישור תשלום קטן כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד. האישור יבוטל ואתה לא תחויב.</p>");
        f1073b.put("LOG_IN_TO_PAYPAL|AU", "היכנס עם PayPal");
        f1073b.put("LOG_IN_TO_PAYPAL|GB", "היכנס עם PayPal");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם השותף.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך ולחץ על סמל גלגל השיניים. עבור אל <strong>אבטחה</strong>, בחר <strong>היכנס עם PayPal</strong> והסר שותף זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של השותף.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של השותף.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> שלך והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם השותף.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך ולחץ על סמל גלגל השיניים. עבור אל <strong>אבטחה</strong>, בחר <strong>היכנס עם PayPal</strong> והסר שותף זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של השותף.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם השותף.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך ולחץ על סמל גלגל השיניים. עבור אל <strong>אבטחה</strong>, בחר <strong>היכנס עם PayPal</strong> והסר שותף זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של השותף.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך, לחץ על סמל גלגל השיניים בפינה הימנית העליונה, בחר <strong>מרכז האבטחה</strong>, בחר <strong>היכנס עם PayPal</strong> והסר את בעל העסק. אם אתה עדיין משתמש באתר הקלאסי, עבור אל <strong>הפרופיל שלי</strong>, בחר <strong>הגדרות החשבון שלי</strong>, בחר <strong>היכנס עם PayPal</strong> והסר את בעל העסק.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם השותף.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך ותחת הגדרות ה<strong>פרופיל</strong>, עבור אל <strong>היכנס עם PayPal</strong> והסר שותף זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של השותף.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.it, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> שלך והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> שלך והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם השותף.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.ru, לחץ על סמל גלגל השיניים בפינה הימנית העליונה, בחר בלשונית <strong>אבטחה</strong> והסר שותף זה תחת האפשרות <strong>היכנס עם PayPal‏</strong>.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של השותף.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com.tr, לחץ על סמל גלגל השיניים בפינה הימנית העליונה, בחר בלשונית <strong>אבטחה</strong> והסר שותף זה תחת האפשרות <strong>היכנס עם PayPal‏</strong>.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> והסר בעל עסק זה.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1073b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>‎%s‎‏</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        f1074c.put("AMOUNT_MISMATCH", "הסכום הכולל של הפריטים בעגלת הקניות אינו תואם את סכום המכירה.");
        f1074c.put("AUTHORIZATION_ALREADY_COMPLETED", "אישור זה כבר הושלם.");
        f1074c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "לא ניתן לבטל את תוקף האישור.");
        f1074c.put("AUTHORIZATION_EXPIRED", "פג תוקף האישור.");
        f1074c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "מזהה האישור המבוקש לא קיים.");
        f1074c.put("AUTHORIZATION_VOIDED", "האישור בוטל.");
        f1074c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "ניתן לאשר מחדש רק את האישור המקורי, לא אישור מחדש.");
        f1074c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "לא ניתן לבצע אישור מחדש במסגרת תקופת הכיבוד.");
        f1074c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "הסכום חורג מהמגבלה המותרת.");
        f1074c.put("CARD_TOKEN_PAYER_MISMATCH", "לא ניתן לגשת לפרטי הכרטיס השמורים.");
        f1074c.put("CREDIT_CARD_CVV_CHECK_FAILED", "פרטי הכרטיס לא תקפים. תקן ושלח שוב.");
        f1074c.put("CREDIT_CARD_REFUSED", "הכרטיס נדחה.");
        f1074c.put("CURRENCY_MISMATCH", "על מטבע האיסוף להיות זהה למטבע האישור.");
        f1074c.put("CURRENCY_NOT_ALLOWED", "PayPal אינה תומכת במטבע זה כעת.");
        f1074c.put("DATA_RETRIEVAL", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        f1074c.put("DUPLICATE_REQUEST_ID", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        f1074c.put("EXPIRED_CREDIT_CARD", "פג תוקף הכרטיס");
        f1074c.put("EXPIRED_CREDIT_CARD_TOKEN", "הפרטים של כרטיס זה כבר אינם נמצאים ברשומות.\nשלח שוב.");
        f1074c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "התכונה אינה נתמכת עבור ספק זה.");
        f1074c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "כבר בוצע החזר חלקי עבור עסקה זו.");
        f1074c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "תשלום מיידי אינו נתמך עבור המטרה (Intent) המבוקשת.");
        f1074c.put("INSTRUMENT_DECLINED", "שיטת התשלום שבחרת לא התקבלה. בחר שיטה אחרת.");
        f1074c.put("INSUFFICIENT_FUNDS", "הקונה לא יכול לשלם - מחסור בכסף.");
        f1074c.put("INTERNAL_SERVICE_ERROR", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        f1074c.put("INVALID_ACCOUNT_NUMBER", "מספר חשבון זה לא קיים.");
        f1074c.put("INVALID_ARGUMENT", "העסקה נדחתה עקב סיבות טכניות");
        f1074c.put("INVALID_CITY_STATE_ZIP", "שילוב לא חוקי של עיר/מדינה/מיקוד.");
        f1074c.put("INVALID_FACILITATOR_CONFIGURATION", "לא ניתן לעבד את העסקה עקב הגדרת גורם מתווך בלתי-תקפה.");
        f1074c.put("INVALID_PAYER_ID", "שגיאת מערכת (מזהה משלם לא חוקי). נסה שוב מאוחר יותר.");
        f1074c.put("INVALID_RESOURCE_ID", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        f1074c.put("PAYEE_ACCOUNT_INVALID", "לחשבון הספק אין כתובת אימייל מאושרת.");
        f1074c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "ספק זה אינו יכול לקבל תשלומים כעת.");
        f1074c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "לחשבון הספק אין כתובת אימייל מאושרת.");
        f1074c.put("PAYEE_ACCOUNT_RESTRICTED", "ספק זה אינו יכול לקבל תשלומים כעת.");
        f1074c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "החשבון שלך נעול או סגור.");
        f1074c.put("PAYER_ACCOUNT_RESTRICTED", "החשבון שלך מוגבל.");
        f1074c.put("PAYER_CANNOT_PAY", "אינך יכול לשלם עבור עסקה זו באמצעות PayPal‏.");
        f1074c.put("PAYER_EMPTY_BILLING_ADDRESS", "נדרשת כתובת לחיוב עבור עסקאות בכרטיס אשראי שאינן משולמות באמצעות PayPal‏.");
        f1074c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "לא ניתן לגשת לפרטי הכרטיס השמורים.");
        f1074c.put("PAYMENT_APPROVAL_EXPIRED", "פג התוקף של אישור התשלום.");
        f1074c.put("PAYMENT_EXPIRED", "פג תוקף התשלום.");
        f1074c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "המשלם לא אישר את התשלום.");
        f1074c.put("PAYMENT_REQUEST_ID_INVALID", "מזהה העסקה של PayPal לא חוקי. נסה שוב מאוחר יותר.");
        f1074c.put("PAYMENT_STATE_INVALID", "בקשה זו אינה חוקית עקב מצבו הנוכחי של התשלום.");
        f1074c.put("PERMISSION_DENIED", "אין הרשאה לפעולה המבוקשת.");
        f1074c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "ההחזר המבוקש חורג מסכום העסקה המקורית.");
        f1074c.put("REFUND_TIME_LIMIT_EXCEEDED", "עסקה זו ישנה מכדי שניתן יהיה לבצע החזר.");
        f1074c.put("REQUIRED_SCOPE_MISSING", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        f1074c.put("TOO_MANY_REAUTHORIZATIONS", "לא ניתן לבצע אישורים מחדש נוספים לאישור זה.");
        f1074c.put("TRANSACTION_ALREADY_REFUNDED", "כבר בוצע החזר עבור עסקה זו.");
        f1074c.put("TRANSACTION_LIMIT_EXCEEDED", "הסכום חורג מהמגבלה המותרת.");
        f1074c.put("TRANSACTION_REFUSED", "העסקה נדחתה.");
        f1074c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "העסקה נדחתה.");
        f1074c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "הגדרת פרופיל בעל העסק מוגדרת לדחייה אוטומטית של עסקאות מסויימות.");
        f1074c.put("UNKNOWN_ERROR", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        f1074c.put("UNSUPPORTED_PAYEE_COUNTRY", "הארץ אינה נתמכת.");
        f1074c.put("VALIDATION_ERROR", "פרטי התשלום אינם חוקיים. תקן ושלח שוב.");
        f1074c.put("ORDER_ALREADY_COMPLETED", "ההזמנה כבר בוטלה, הושלמה או שתוקפה פג.");
        f1074c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "ההזמנה הגיעה למספר המרבי המותר של אישורים.");
        f1074c.put("ORDER_VOIDED", "ההזמנה בוטלה.");
        f1074c.put("ORDER_CANNOT_BE_VOIDED", "מצב ההזמנה מונע את ביטולה.");
        f1074c.put("INVALID_EXPERIENCE_PROFILE_ID", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        f1074c.put("UNAUTHORIZED_PAYMENT", "בעל העסק אינו מקבל תשלום מסוג זה.");
        f1074c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "המטבע לא נתמך עבור סוג הכרטיס.");
        f1074c.put("DCC_CC_TYPE_NOT_SUPPORTED", "סוג הכרטיס לא נתמך.");
        f1074c.put("ADDRESS_ADDITION_ERROR", "אירעה שגיאה בעת הוספת כתובת למשלוח לחשבון ה-PayPal‏.");
        f1074c.put("DUPLICATE_TRANSACTION", "עסקה כפולה.");
        f1074c.put("INVALID_SHIPPING_ADDRESS", "הכתובת למשלוח שהוזנה אינה חוקית.");
        f1074c.put("PAYMENT_CREATION_ERROR", "אירעה בעיה בהגדרת תשלום זה. בקר באתר PayPal כדי לבדוק את החשבון שלך.");
        f1074c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "אירעה בעיה בהגדרת תשלום זה - פג תוקף הכרטיס שלך. בקר באתר PayPal כדי לבדוק את החשבון שלך.");
        f1074c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "אירעה בעיה בהגדרת תשלום זה - נדרש אמצעי תשלום מיידי, כגון כרטיס אשראי. בקר באתר PayPal כדי לבדוק את החשבון שלך.");
        f1074c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "אירעה בעיה בהגדרת תשלום זה - יש לאשר את הכרטיס. בקר באתר PayPal כדי לבדוק את החשבון שלך.");
        f1074c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "אירעה בעיה בהגדרת תשלום זה - אפליקציה זו מחייבת שהחשבון שלך יכיל מספר טלפון. בקר באתר PayPal כדי לבדוק את החשבון שלך.");
        f1074c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "אירעה בעיה בהגדרת תשלום זה - החשבון צריך להכיל מקור כספי חוקי, כגון חשבון בנק או כרטיס תשלום. בקר באתר PayPal כדי לבדוק את החשבון שלך.");
        f1074c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "אירעה בעיה בהגדרת תשלום זה - היתרה שלך שלילית. בקר באתר PayPal כדי לבדוק את החשבון שלך.");
        f1074c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "אירעה בעיה בהגדרת תשלום זה - הגעת למגבלת השליחה שלך. בקר באתר PayPal כדי לבדוק את החשבון שלך.");
        f1074c.put("AUTH_RC_RISK_FAILURE", "נדחה עקב סיכון.");
        f1074c.put("AUTH_RC_OFAC_BLOCKED_IP", "לקוח לא אושר.");
        f1074c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "לקוח לא אושר.");
        f1074c.put("invalid_user", "שם משתמש/סיסמה שגויים. נסה שוב.");
        f1074c.put("locked_user", "חשבון ה-PayPal שלך ננעל באופן זמני. נסה שוב מאוחר יותר, או עבור אל www.paypal.co.il כדי לבטל את נעילת חשבון ה-PayPal שלך באופן מיידי.");
        f1074c.put("max_attempts_exceeded", "חרגת ממספר ניסיונות הכניסה המרבי. נסה שוב מאוחר יותר.");
        f1074c.put("invalid_request", "אירעה שגיאה.");
        f1074c.put("unauthorized_client", "הבקשה לא אושרה.");
        f1074c.put("access_denied", "הבקשה לא אושרה.");
        f1074c.put("unsupported_response_type", "אירעה שגיאה.");
        f1074c.put("invalid_scope", "הבקשה לא אושרה.");
        f1074c.put("server_error", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        f1074c.put("temporarily_unavailable", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        f1074c.put("stepup_required", "לא ניתן להשלים את כניסתך לחשבון בשלב זה. נסה שוב מאוחר יותר, או עבור אל www.paypal.co.il כדי לפתור בעיות אבטחה אפשריות עם חשבון ה-PayPal שלך.");
    }

    public final String mo2147a() {
        return "he";
    }

    public final /* synthetic */ String mo2148a(Enum enumR, String str) {
        fw fwVar = (fw) enumR;
        String str2 = fwVar.toString() + "|" + str;
        return f1073b.containsKey(str2) ? (String) f1073b.get(str2) : (String) f1072a.get(fwVar);
    }

    public final String mo2149a(String str) {
        return (String) f1074c.get(str);
    }
}
